@endpoint=https://ai.hdqmjs.com/
@token=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE2LCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjE5NywiaG91ciI6MTYsIm1pbnV0ZSI6MTYsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjI0OTAwMDAwMCwic2Vjb25kIjoxNiwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiIzOGE0MjNiYzU4M2Y0ZjQ5YTllZDkwMWI4MmJkN2Y4NCIsInJlZnJlc2hfdG9rZW4iOiJlNTg2YjdiNDk3YzY0N2ZlOTI5YjRmZTU1Yzk0YThkNCIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjIsImRlcHRfaWQiOjMsInVzZXJuYW1lIjoiemYwMSIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI1NTU5Mzc2Iiwicm9sZV9jb2RlcyI6WyJBU1MiXX0.O9y_EAjRNPd2BOhvGOhzbYr6rYCvF5IAQV3GbWPqYys

### 查询企业信息库
GET {{endpoint}}/admin/companyinfo/page
Authorization: Bearer {{token}}

### 通过id查询企业数据库
GET {{endpoint}}/admin/companyinfo/30
Authorization: Bearer {{token}}
