@endpoint=https://api.mock.smallsaas.cn

### 原测试数据
POST http://47.119.113.172:8380/api.page.design.page/loadPageInfo
content-type: application/json

{
    "id": 75
}



## 动态表单

### 获取动态表单数据
GET {{endpoint}}/form?id=10 HTTP/1.1
# User-Agent: rest-client

### 保存动态表单数据
POST {{endpoint}}/form/10 HTTP/1.1
content-type: application/json

{
    "fields": [
      {
        "__config__": {
          "label": "账号",
          "labelWidth": null,
          "showLabel": true,
          "tag": "el-input",
          "tagIcon": "input",
          "defaultValue": "admin",
          "required": true,
          "layout": "colFormItem",
          "regList": [],
          "formId": 101,
          "renderKey": 1621415022993
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "请输入账号",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "disabled": false,
        "__vModel__": "account"
      },
      {
        "__config__": {
          "label": "密码",
          "showLabel": true,
          "labelWidth": null,
          "tag": "el-input",
          "tagIcon": "password",
          "layout": "colFormItem",
          "required": true,
          "regList": [
            {
              "pattern": "/0-9/",
              "message": "密码只能是纯数字"
            }
          ],
          "formId": 102,
          "renderKey": 1621415025493
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "请输入密码",
        "show-password": true,
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "disabled": false,
        "__vModel__": "password"
      },
      {
        "__config__": {
          "label": "性别",
          "showLabel": true,
          "labelWidth": null,
          "tag": "el-select",
          "tagIcon": "select",
          "layout": "colFormItem",
          "required": true,
          "regList": [],
          "formId": 103,
          "renderKey": 1621415255861
        },
        "__slot__": {
          "options": [
            {
              "label": "男",
              "value": 1
            },
            {
              "label": "女",
              "value": 2
            }
          ]
        },
        "placeholder": "请选择性别",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "disabled": false,
        "filterable": false,
        "multiple": false,
        "__vModel__": "sex"
      },
      {
        "__config__": {
          "label": "单选框组",
          "labelWidth": null,
          "showLabel": true,
          "tag": "el-radio-group",
          "tagIcon": "radio",
          "layout": "colFormItem",
          "optionType": "default",
          "regList": [],
          "required": false,
          "border": false,
          "formId": 104,
          "renderKey": 1621415304568
        },
        "__slot__": {
          "options": [
            {
              "label": "选项一",
              "value": 1
            },
            {
              "label": "选项二",
              "value": 2
            }
          ]
        },
        "style": {},
        "size": "medium",
        "disabled": false,
        "__vModel__": "field104"
      },
      {
        "__config__": {
          "label": "多选框组",
          "tag": "el-checkbox-group",
          "tagIcon": "checkbox",
          "defaultValue": [],
          "showLabel": true,
          "labelWidth": null,
          "layout": "colFormItem",
          "optionType": "default",
          "required": false,
          "regList": [],
          "border": false,
          "formId": 105,
          "renderKey": 1621415342008
        },
        "__slot__": {
          "options": [
            {
              "label": "选项一",
              "value": 1
            },
            {
              "label": "选项二",
              "value": 2
            },
            {
              "label": "选项三",
              "value": 3
            }
          ]
        },
        "style": {},
        "size": "medium",
        "disabled": false,
        "__vModel__": "field105"
      },
      {
        "__config__": {
          "label": "开关",
          "tag": "el-switch",
          "tagIcon": "switch",
          "defaultValue": false,
          "showLabel": true,
          "labelWidth": null,
          "layout": "colFormItem",
          "required": true,
          "regList": [],
          "formId": 106,
          "renderKey": 1621415361475
        },
        "style": {},
        "disabled": false,
        "active-text": "",
        "inactive-text": "",
        "active-color": null,
        "inactive-color": null,
        "active-value": true,
        "inactive-value": false,
        "__vModel__": "field106"
      },
      {
        "__config__": {
          "label": "日期选择",
          "tag": "el-date-picker",
          "tagIcon": "date",
          "defaultValue": null,
          "showLabel": true,
          "labelWidth": null,
          "layout": "colFormItem",
          "required": true,
          "regList": [],
          "formId": 109,
          "renderKey": 1621415374360
        },
        "placeholder": "请选择日期选择",
        "type": "date",
        "style": {
          "width": "100%"
        },
        "disabled": false,
        "clearable": true,
        "format": "yyyy-MM-dd",
        "value-format": "yyyy-MM-dd",
        "readonly": false,
        "__vModel__": "field109"
      },
      {
        "__config__": {
          "layout": "rowFormItem",
          "tagIcon": "row",
          "layoutTree": true,
          "formId": 112,
          "renderKey": 1621415404383,
          "componentName": "row112",
          "children": [
            {
              "__config__": {
                "label": "单行文本",
                "labelWidth": null,
                "showLabel": true,
                "tag": "el-input",
                "tagIcon": "input",
                "required": true,
                "layout": "colFormItem",
                "regList": [],
                "formId": 113,
                "renderKey": 1621415432107
              },
              "__slot__": {
                "prepend": "",
                "append": ""
              },
              "placeholder": "请输入单行文本",
              "style": {
                "width": "100%"
              },
              "clearable": true,
              "prefix-icon": "",
              "suffix-icon": "",
              "maxlength": null,
              "show-word-limit": false,
              "readonly": false,
              "disabled": false,
              "__vModel__": "field113"
            },
            {
              "__config__": {
                "label": "多行文本",
                "labelWidth": null,
                "showLabel": true,
                "tag": "el-input",
                "tagIcon": "textarea",
                "required": true,
                "layout": "colFormItem",
                "regList": [],
                "formId": 114,
                "renderKey": 1621415438457
              },
              "type": "textarea",
              "placeholder": "请输入多行文本",
              "autosize": {
                "minRows": 4,
                "maxRows": 4
              },
              "style": {
                "width": "100%"
              },
              "maxlength": null,
              "show-word-limit": false,
              "readonly": false,
              "disabled": false,
              "__vModel__": "field114"
            }
          ]
        },
        "type": "default",
        "justify": "start",
        "align": "top"
      }
    ],
    "formRef": "elForm",
    "formModel": "formData",
    "size": "medium",
    "labelPosition": "left",
    "labelWidth": 100,
    "formRules": "rules",
    "gutter": 0,
    "disabled": false,
    "formBtns": true,
    "unFocusedComponentBorder": false
  }


## 原型页面

### 企业自查入江口

GET {{endpoint}}/form?id=10 HTTP/1.1
content-type: application/json
###

POST {{endpoint}}/form/10 HTTP/1.1
content-type: application/json

{
    "fields": [
      {
        "__config__": {
          "layout": "rowFormItem",
          "tagIcon": "row",
          "componentName": "自查事项",
          "children": [
            {
              "__config__": {
                "label": "自查项 #1",
                "showLabel": true,
                "tag": "el-input",
                "tagIcon": "input",
                "required": false,
                "layout": "colFormItem"
              },
              "readonly": false,
              "inputBlock": true,
              "placeholder": "请输入自查说明",
              "__vModel__": "check1"
            },
            {
              "__config__": {
                "label": "自查项 #2",
                "labelWidth": null,
                "showLabel": true,
                "tag": "el-radio-group",
                "tagIcon": "input",
                "required": false,
                "layout": "colFormItem"
              },
              "__slot__": {
                "options":[
                  { "label": "选项 #1", "value": "1" },
                  { "label": "选项 #1", "value": "2" }
                ]
              },
              "readonly": false,
              "inputBlock": true,
              "placeholder": "请选择自查项 #2",
              "__vModel__": "check2"
            },
            {
              "__config__": {
                "label": "自查项 #3",
                "labelWidth": null,
                "showLabel": true,
                "tag": "el-checkbox-group",
                "tagIcon": "input",
                "required": false,
                "layout": "colFormItem"
              },
              "__slot__": {
                "options":[
                  { "label": "是", "value": "1" },
                  { "label": "否", "value": "2" },
                  { "label": "不知道", "value": "3" },
                  { "label": "技术咨询", "value": "4" }
                ]
              },
              "readonly": false,
              "inputBlock": true,
              "__vModel__": "check3"
            },
            {
              "__config__": {
                "label": "自查项 #4",
                "labelWidth": null,
                "showLabel": true,
                "tag": "el-input",
                "tagIcon": "input",
                "required": false,
                "layout": "colFormItem"
              },
              "placeholder": "请输入自查项4",
              "readonly": false,
              "inputBlock": true,
              "__vModel__": "date"
            }
          ]
        }
      }

    ],
    "formRef": "elForm",
    "formModel": "formData",
    "size": "medium",
    "labelPosition": "left",
    "labelWidth": 100,
    "formRules": "rules",
    "gutter": 0,
    "disabled": false,
    "formBtns": true,
    "unFocusedComponentBorder": false
  }




### 复工

POST {{endpoint}}/form/10 HTTP/1.1
content-type: application/json

{
    "fields": [
      {
        "__config__": {
          "layout": "rowFormItem",
          "tagIcon": "row",
          "layoutTree": true,
          "formId": 112,
          "renderKey": 1621415404383,
          "componentName": "我的",
          "children": [
            {
							"__config__": {
								"label": "企业名称",
								"showLabel": true,
								"tag": "el-input",
								"tagIcon": "input",
								"required": false,
								"layout": "colFormItem"
							},
							"readonly": false,
							"inputBlock": true,
							"placeholder": "请输入企业名称",
							"__vModel__": "field1"
						},

						{
							"__config__": {
								"label": "企业地址",
								"showLabel": true,
								"tag": "el-input",
								"tagIcon": "input",
								"required": false,
								"layout": "colFormItem"
							},
							"readonly": false,
							"inputBlock": true,
							"placeholder": "请输入企业地址",
							"__vModel__": "field2"
						},
						{
							"__config__": {
								"label": "法定代表人",
								"showLabel": true,
								"tag": "el-input",
								"tagIcon": "input",
								"required": false,
								"layout": "colFormItem"
							},
							"readonly": false,
							"inputBlock": true,
							"placeholder": "请输入法定代表人",
							"__vModel__": "field2"
						},
						{
							"__config__": {
								"label": "进馆人数",
								"labelWidth": null,
								"showLabel": true,
								"tag": "el-input",
								"tagIcon": "number",
								"required": false,
								"layout": "colFormItem"
							},
							"placeholder": "请输入进馆人数",
							"readonly": false,
							"inputBlock": true,
							"__vModel__": "field3"
						}
          ]
        },
        "type": "default",
        "justify": "start",
        "align": "top"
      }
    ],
    "formRef": "elForm",
    "formModel": "formData",
    "size": "medium",
    "labelPosition": "left",
    "labelWidth": 100,
    "formRules": "rules",
    "gutter": 0,
    "disabled": false,
    "formBtns": false,
    "unFocusedComponentBorder": false
  }







## 动态列表 

### 获取动态列表设计数据 
GET {{endpoint}}/form?id=101


### 保存动态列表
POST {{endpoint}}/form/101
content-type: application/json

{
    "loadApi": "https://www.fastmock.site/mock/96df9e8fb08bfe844b3e565f5a3206fe/test/api/pub/getList",
    "itemNavigation": "/articleDetail/index?id=&title",
    "tabConfig":
     {
       "field":"type",
       "show": true,
       "list":[
          {
              "name":"全部",
              "value":"0"
          },
          {
              "name":"时尚搭配",
              "value":"100"
          },
          {
             "name":"行业咨询",
             "value":"200"
          }
       ]
    },
    "response":
    {
        "list":"type.list",
        "total":"type.total"
    },
    "request":
    {
       "fixed":"type",
       "default":
        {
           "type":"0"
        },
       "pn":"pageNo",
       "ps":"pageSize"
    },
    "modules":
    [
        {
            "type":"custom_component",
            "name":"自定义组件",
            "key":"5243e64e-40ca-8b50-cdce-1623039409345"
        }
    ],
    "moduleData":
    {
        "5243e64e-40ca-8b50-cdce-1623039409345":
        {
            "id":"5243e64e-40ca-8b50-cdce-1623039409345",
            "name":"ArticleItem"
        }
    }
}
