@endpoint=https://ai.hdqmjs.com


### 列表测试数据


### 测试获取数据
## GET https://ai.hdqmjs.com/custom/ids?id=10
GET {{endpoint}}/custom?id=17 HTTP/1.1
content-type: application/json
User-Agent: rest-client


### 保存数据
//POST {{endpoint}}/custom/ids HTTP/1.1
POST {{endpoint}}/custom/17 HTTP/1.1
content-type: application/json

{
    "id": 10,
    "name":"Hendry",
    "salary":"61888",
    "age":"26"
}


