@endpoint=https://ai.hdqmjs.com

### 原测试数据
GET https://www.fastmock.site/mock/96df9e8fb08bfe844b3e565f5a3206fe/test/api/pub/getList?type=0


## 动态列表

### 获取动态列表数据
GET {{endpoint}}/data?id=10 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存动态列表数据
POST {{endpoint}}/data/10 HTTP/1.1
content-type: application/json

{
    "type": {
      "list": [
        {
          "type": "100",
          "title": "的撒开发和建设的规100",
          "desc": "阿迪舒服哈森岛宽晃发的颂古非今阿萨德个发货速度发定时发送地方",
          "time": "2020-01-01",
          "img": "https://66861.s81i.faiusr.com/4/103/AFEIrYoEEAQYACDm84HWBSiN0KWQAjCKAjjHAUBn.png"
        },
        {
          "type": "200",
          "title": "的撒开发和建设的规200",
          "desc": "阿迪舒服哈森岛宽晃发的颂古非今阿萨德个发货速度发定时发送地方",
          "time": "2020-01-01",
          "img": "https://66861.s81i.faiusr.com/4/103/AFEIrYoEEAQYACDm84HWBSiN0KWQAjCKAjjHAUBn.png"
        }
      ],
      "total": 2
    }
  }


## 动态页面

### 获取动态页面数据
GET {{endpoint}}/data?id=200 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存动态页面数据
POST {{endpoint}}/data/200 HTTP/1.1
content-type: application/json

{
  "code": 200,
  "data": {
    "daysPassed": 5,
    "list": [
      {
        "type": "100",
        "title": "的撒开发和建设的规100",
        "desc": "阿迪舒服哈森岛宽晃发的颂古非今阿萨德个发货速度发定时发送地方",
        "time": "2020-01-01",
        "img": "https://66861.s81i.faiusr.com/4/103/AFEIrYoEEAQYACDm84HWBSiN0KWQAjCKAjjHAUBn.png"
      },
      {
        "type": "200",
        "title": "的撒开发和建设的规200",
        "desc": "阿迪舒服哈森岛宽晃发的颂古非今阿萨德个发货速度发定时发送地方",
        "time": "2020-01-01",
        "img": "https://66861.s81i.faiusr.com/4/103/AFEIrYoEEAQYACDm84HWBSiN0KWQAjCKAjjHAUBn.png"
      }
    ],
    "total": 2
  }
}
