@endpoint = https://ai.hdqmjs.com


### 获取关键字组 （自动识别）
GET {{endpoint}}/form?id=96623

### 更改关键字组
### 更改方法：在keyWordGroup中增加关键词即可
POST {{endpoint}}/form/96623
Content-Type: application/json

{
    "keyWordGroup":[
        "游泳", "健身", "攀岩", "滑雪", "滑冰", "射箭", "田径", "羽毛球", "皮划艇", "棒球", "篮球", "拳击", "自行车", "击剑", "足球", "手球", "马术", "曲棍球", "柔道", "现代五项", "体操", "赛艇", "帆船", "射击", "排球", "垒球", "兵乒球", "跆拳道", "网球", "铁人三项", "举重", "摔跤", "冬季两项", "冰壶", "冰球", "潜水", "滑水", "摩托艇", "救生", "健美操", "技巧", "高尔夫球", "保龄球", "掷球", "台球", "藤球", "壁球", "橄榄球", "软式网球", "热气球", "运动飞机", "跳伞", "滑翔", "航空模型", "车辆模型", "航海模型", "定向", "业余无线电", "围棋", "国际象棋", "中国象棋", "桥牌", "武术", "健身气功", "登山", "汽车", "摩托车", "轮滑", "毽球", "门球", "舞龙舞狮", "龙舟", "钓鱼", "风筝", "信鸽", "体育舞蹈", "健美", "拔河", "飞镖", "电子竞技","蹦床","瑜伽"
    ]
}