@endpoint=https://api.mock.smallsaas.cn

### 原测试数据
POST http://47.119.113.172:8380/api.page.design.page/loadPageInfo
content-type: application/json

{
    "id": 75
}



## 动态表单

### 获取动态表单数据
GET {{endpoint}}/form?id=10 HTTP/1.1
# User-Agent: rest-client

## 原型页面

### 复工

POST {{endpoint}}/form/11 HTTP/1.1
content-type: application/json

{
  "loadApi": "https://api.mock.smallsaas.cn/data?id=11",
  "fields": [{
      "__config__": {
        "label": "企业名称",
        "showLabel": true,
        "tag": "el-input",
        "tagIcon": "input",
        "required": false,
        "layout": "colFormItem"
      },
      "readonly": false,
      "inputBlock": true,
      "placeholder": "请输入企业名称",
      "__vModel__": "enterpriseName"
    },

    {
      "__config__": {
        "label": "企业地址",
        "showLabel": true,
        "tag": "el-input",
        "tagIcon": "input",
        "required": false,
        "layout": "colFormItem"
      },
      "readonly": false,
      "inputBlock": true,
      "placeholder": "请输入企业地址",
      "__vModel__": "enterpriseAddress"
    },
    {
      "__config__": {
        "label": "法定代表人",
        "showLabel": true,
        "tag": "el-input",
        "tagIcon": "input",
        "required": false,
        "layout": "colFormItem"
      },
      "readonly": false,
      "inputBlock": true,
      "placeholder": "请输入法定代表人",
      "__vModel__": "legalPerson"
    },
    {
      "__config__": {
        "label": "进馆人数",
        "labelWidth": null,
        "showLabel": true,
        "tag": "el-input",
        "tagIcon": "number",
        "required": false,
        "layout": "colFormItem"
      },
      "placeholder": "请输入进馆人数",
      "readonly": false,
      "inputBlock": true,
      "__vModel__": "number"
    }
  ]
}

### 页面测试数据
POST  {{endpoint}}/data/11 HTTP/1.1
content-type: application/json

{
  "days": 15,
  "enterpriseName": "GZ",
  "enterpriseAddress": "广州",
  "legalPerson": "张三",
  "number": 30
}

### 页面测试数据
GET {{endpoint}}/data?id=11 HTTP/1.1
content-type: application/json

