@endpoint = https://ai.hdqmjs.com

### 获取用户token
GET {{endpoint}}/data?id=8000
### 用户列表
POST {{endpoint}}/data/8000 HTTP/1.1
Content-Type: application/json

{
    "zfUser":"eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE4LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjE5OSwiaG91ciI6MTgsIm1pbnV0ZSI6NDksIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjIzMTAwMDAwMCwic2Vjb25kIjoyNCwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiJjNTZhM2VkYmZjM2E0YTI4YmQ5NWYxYjhhZjVkZDAyNyIsInJlZnJlc2hfdG9rZW4iOiIxMjgwMDBkZTJlMDQ0YjhmYmQ2NWZjNzcwZjBmNzRmNSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6NTEsInVzZXJuYW1lIjoiemYwOTAiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjo1LCJ0aW1lX3N0YW1wIjoiMTYyNTc0MTM2NCIsInJvbGVfY29kZXMiOlsiUVlZSCJdfQ.NeCbqQ1H6hycpkq-rXTQ0h4aG-3pXQUDNSeiw4O9Zj4",
    "qyUser":"eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE4LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjE5OSwiaG91ciI6MTgsIm1pbnV0ZSI6NTMsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjE5NTAwMDAwMCwic2Vjb25kIjo5LCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiI1NGZhNTQzZTdhZTI0NjAxOTZhMWI4NjY4ODYzMjhjNSIsInJlZnJlc2hfdG9rZW4iOiI2MTBlN2UwNzA1ODU0ZmEzYjY5YzllMDAyNTQ3OWZkMyIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6NTIsInVzZXJuYW1lIjoicXkwOTAiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjo1LCJ0aW1lX3N0YW1wIjoiMTYyNTc0MTU4OSIsInJvbGVfY29kZXMiOlsiUVlZSCJdfQ.OfAkukB_jGohykx4NQqzu4aEEDOkIbSVPHD_iKf8Lxo"
}