@endpoint = https://rt.zbsoft.top
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjIsImRheU9mV2VlayI6Ik1PTkRBWSIsImRheU9mWWVhciI6MjE0LCJob3VyIjoxMywibWludXRlIjozNCwibW9udGgiOiJBVUdVU1QiLCJtb250aFZhbHVlIjo4LCJuYW5vIjo5MDUwMDAwMDAsInNlY29uZCI6MTMsInllYXIiOjIwMjEsImNocm9ub2xvZ3kiOnsiY2FsZW5kYXJUeXBlIjoiaXNvODYwMSIsImlkIjoiSVNPIn19LCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3NfdG9rZW4iOiJmNjhlMjk4NDIyMDE0ZmE2OWNjN2NlNjgzOTAyOTA0NCIsInJlZnJlc2hfdG9rZW4iOiI3YTJhOTY4Mjg4YmU0ZGJkYWQ0MDdkNDU5NWJhNTNhMCIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MTMyLCJkZXB0X2lkIjo3LCJ1c2VybmFtZSI6InpmcnkwMTAiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjoyLCJ0aW1lX3N0YW1wIjoiMTYyNzAxODQ1MyIsInJvbGVfY29kZXMiOlsiQVNTIl0sIm9wZW5faWQiOiJveU9xQjVSSHJfZ2JJRGVYR0MzSDFIaEZaN25BIiwiYXBwIjoiaW50ZXJuYWwifQ.m8l_vL4kLd-yoAUYZnI665OsyDQIkoc_oail_QE0p6Y

### 字典测试
GET {{endpoint}}/admin/dict/page
Authorization: Bearer {{token}}


### 场馆类型
GET https://ai.hdqmjs.com/api/u/icon
# Authorization: Bearer {{token}}