@endpoint = https://ai.hdqmjs.com
### 获取企业我的列表数据
GET {{endpoint}}/data?id=5555
### 更改企业我的列表数据
### icon对应图标库中的全名
POST {{endpoint}}/data/5555
Content-Type: application/json

{
    "list":[
        {"icon":"listZc","title":"自查记录","nav":"/companyHome/my/selfInspectionRecord"},
        {"icon":"listZf","title":"执法记录","nav":"/companyHome/my/lawEnforcementRecord"},
        {"icon":"listFg","title":"复工记录","nav":"/companyHome/my/returnToWorkRecord"},
        {"icon":"listGgqyxx","title":"更改企业信息","nav":"/companyHome/my/reCompanyMes"}
    ]
}

### 获取街道我的列表数据
GET {{endpoint}}/data?id=5556
### 更改街道我的列表数据
### icon对应图标库中的全名
POST {{endpoint}}/data/5556
Content-Type: application/json

{
    "list":[
        {"icon":"record","title":"我的上报","nav":"/street/my/myReport"},
        {"icon":"typeJdsb","title":"辖区内企业","nav":"/street/getCompany"}
    ]
}



### 获取执法我的列表数据
GET {{endpoint}}/data?id=5557
### 更改执法我的列表数据
### icon对应图标库中的全名
POST {{endpoint}}/data/5557
Content-Type: application/json

{
    "list":[
        {"icon":"record","title":"我的执法记录","nav":"/enforcement/myEnforcement"}
    ]
}