@endpoint=https://api.mock.smallsaas.cn


## 动态页面


### 保存动态列表
POST {{endpoint}}/form/300
content-type: application/json

{  
    "version": "1",
    "name": "page_home",
    "title": "自查详情",
    "pageStyle": {},
    "loadApi": "https://api.mock.smallsaas.cn/data?id=200",
    "request": {},
    "response":
    {
      "data": "data"
    },
    "container":{
      "padding": "10px",
      "margin": "10px",
      "fill": "white",
      "stroke": 
      {
         "color": "lightgray",
         "lineWidth": "1px"
      },
      "shadow":
      {
         "radius": 5
      },
      "corner": "8px",
      "spacing": "1em"
   },
  "modules": [
    {
      "type": "autoform",
      "key": "96afd71a-c8d5-11eb-aca5-0800271e55b7",
      "name": "动态表单组件",
      "container":{}
    },
    {
      "container":{
      },
      "type": "autolist",
      "key": "5243e64e-40ca-8b50-cdce-1623039409345",
      "name": "动态列表组件",
      "binding": 
      {
        "profile": {},
        "list":"list",
        "total":"total"
      },
      "bindingTarget": "data"
    }
  ], 
  "moduleData":
    {
        "5243e64e-40ca-8b50-cdce-1623039409345":
        {
          "loadApi": "https://www.fastmock.site/mock/96df9e8fb08bfe844b3e565f5a3206fe/test/api/pub/getList",
          "tabConfig": {},
          "response":
          {
              "list":"type.list",
              "total":"type.total"
          },
          "request":
          {
            "fixed":"type",
            "default":
              {
                "type":"0"
              },
            "pn":"pageNo",
            "ps":"pageSize"
          },
          "modules":
          [
              {
                  "type":"custom_component",
                  "name":"自定义组件",
                  "key":"5243e64e-40ca-8b50-cdce-1623039409345"
              }
          ],
          "moduleData":
          {
              "5243e64e-40ca-8b50-cdce-1623039409345":
              {
                  "id":"5243e64e-40ca-8b50-cdce-1623039409345",
                  "name":"ArticleItem"
              }
          }
        }, 
        "96afd71a-c8d5-11eb-aca5-0800271e55b7":
      {
        "loadApi": "https://api.mock.smallsaas.cn/data?id=311",
        "formBtns": false,
        "fields": [{
            "__config__": {
                "layout": "rowFormItem",
                "tagIcon": "row",
                "layoutTree": true,
                "formId": 112,
                "renderKey": 1621415404383,
                "componentName": "企业信息",
                "children": [
                  {
                    "__config__": {
                      "label": "名称",
                      "labelWidth": null,
                      "showLabel": true,
                      "tag": "el-input",
                      "tagIcon": "input",
                      "required": false,
                      "layout": "colFormItem",
                      "formId": 113,
                      "renderKey": 1621415432107
                    },
                    "readonly": true,
                    "__vModel__": "companyName"
                  },
                {
                  "__config__": {
                    "label": "法定代表人",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "__vModel__": "peple"
                },
                {
                  "__config__": {
                    "label": "场所地址",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "__vModel__": "address"
                },
                {
                  "__config__": {
                    "label": "成立日期",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "__vModel__": "date"
                },
                {
                  "__config__": {
                    "label": "联系电话",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "__vModel__": "phone"
                }
              ]
            }
          },
          {
            "__config__": {
              "layout": "rowFormItem",
              "tagIcon": "row",
              "layoutTree": true,
              "formId": 112,
              "renderKey": 1621415404383,
              "componentName": "证件",
              "children": [{
                  "__config__": {
                    "label": "营业执照",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-upload",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "max-count": 1,
                  "deletable": false,
                  "__vModel__": "businessImage"
                },
                {
                  "__config__": {
                    "label": "许可证",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-upload",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "max-count": 1,
                  "deletable": false,
                  "__vModel__": "licenseImage"
                }
              ]
            }
          },
          {
            "__config__": {
              "layout": "rowFormItem",
              "tagIcon": "row",
              "layoutTree": true,
              "formId": 112,
              "renderKey": 1621415404383,
              "componentName": "现场照片",
              "children": [{
                "__config__": {
                  "label": "",
                  "labelWidth": null,
                  "showLabel": true,
                  "tag": "el-upload",
                  "tagIcon": "input",
                  "required": false,
                  "layout": "colFormItem",
                  "formId": 113,
                  "renderKey": 1621415432107
                },
                "readonly": true,
                "max-count": 1,
                "deletable": false,
                "__vModel__": "sceneImage"
              }]
            }
          },
          {
            "__config__": {
              "layout": "rowFormItem",
              "tagIcon": "row",
              "layoutTree": true,
              "formId": 112,
              "renderKey": 1621415404383,
              "componentName": "自查选项",
              "children": [{
                  "__config__": {
                    "label": "自查项 #1",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "max-count": 1,
                  "deletable": false,
                  "__vModel__": "check1"
                },
                {
                  "__config__": {
                    "label": "自查项 #2",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "max-count": 1,
                  "deletable": false,
                  "__vModel__": "check2"
                },
                {
                  "__config__": {
                    "label": "自查项 #3",
                    "labelWidth": null,
                    "showLabel": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "formId": 113,
                    "renderKey": 1621415432107
                  },
                  "readonly": true,
                  "max-count": 1,
                  "deletable": false,
                  "__vModel__": "check3"
                }
              ]
            }
          }
        ]
      }
    }
}

### 页面测试数据
POST {{endpoint}}/data/311 HTTP/1.1
content-type: application/json

{
  "companyName": "北京天翔文化产业有限公司",
  "peple": "王伟伟",
  "address": "北京市海淀区文化产业园A8901",
  "date": "2020年3年1日",
  "phone": "13666000111",
  "licenseImage": [{
    "url": "require('../../static/images/empty.png')",
    "isImage": true
  }],
  "businessImage": [{
    "url": "require('../../static/images/empty.png')",
    "isImage": true
  }],
  "sceneImage": [{
      "url": "require('../../static/images/empty.png')",
      "isImage": true
    },
    {
      "url": "require('../../static/images/empty.png')",
      "isImage": true
    },
    {
      "url": "require('../../static/images/empty.png')",
      "isImage": true
    }
  ],
  "check1": "选项内容",
  "check2": "选项#1",
  "check3": "技术咨询"
}