@endpoint = https://ai.hdqmjs.com
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjEzLCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjIyNSwiaG91ciI6MTQsIm1pbnV0ZSI6NCwibW9udGgiOiJBVUdVU1QiLCJtb250aFZhbHVlIjo4LCJuYW5vIjo1MjcwMDAwMDAsInNlY29uZCI6NTcsInllYXIiOjIwMjEsImNocm9ub2xvZ3kiOnsiaWQiOiJJU08iLCJjYWxlbmRhclR5cGUiOiJpc284NjAxIn19LCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3NfdG9rZW4iOiI5MTVlYjY0MjBiOTg0ZjdjYmVjMjU4ZmUyMWE3ZmNiNiIsInJlZnJlc2hfdG9rZW4iOiI1NmU1NGRmYTg5YTM0OTFmYTQ4MDBhYWIwNjgxYmI1NiIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MSwiZGVwdF9pZCI6ODYsInVzZXJuYW1lIjoiYWRtaW4iLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjowLCJ0aW1lX3N0YW1wIjoiMTYyNzk3MDY5NyIsInJvbGVfY29kZXMiOlsiUk9MRV9BRE1JTiJdLCJuaWNrbmFtZSI6Iui2hee6p-euoeeQhuWRmCJ9.vIw5niWGGwkIUrNI8yu9iYWfLm3HqdFGzkaGV1cKzSU
GET  {{endpoint}}/admin/sysnotice/page
Authorization: Bearer {{token}}