@endpoint = https://ai.hdqmjs.com

## 动态列表主页
# 跳转路由
# 前往各个子项
# 本页只提供路由跳转功能
### 获取列表主页数据
GET {{endpoint}}/form?id=2004
content-type: application/json


### 保存列表主页数据
POST {{endpoint}}/form/2004
content-type: application/json

{
    "version":"1",
    "name":"enforcementDetails",
    "title":"企业详情",
    "pageStyle":{
        "padding":"10px",
        "background":"#EFEFEF"
    },
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"autoform",
            "key":"autoform-7812-ad64-398a-451231561122",
            "name":"",
            "container":{
                "background":"white"
            }
        },
        {
            "type":"navlist",
            "key":"navlists-7112-5154-2131-555256465455",
            "name":"更多",
            "container":{
                "grid-template-columns":"repeat(3, 33.33333333%)"
            }
        }
    ],
    "moduleData":{
        "autoform-7812-ad64-398a-451231561122":{
            "loadApi":"https://ai.hdqmjs.com/api/u/companyInfo",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"企业信息",
                        "children":[
                            {
                                "__config__":{
                                    "label":"名称",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"名称",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"name"
                            },
                            {
                                "__config__":{
                                    "label":"法定代表人",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"法定代表人",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"legalRepresentative"
                            },
                            {
                                "__config__":{
                                    "label":"场所地址",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"场所地址",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"address"
                            },
                            {
                                "__config__":{
                                    "label":"营业执照",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"营业执照",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"licenceNo"
                            },
                            {
                                "__config__":{
                                    "label":"联系电话",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"联系电话",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"personPhone"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "navlists-7112-5154-2131-555256465455":{
            "itemModule":{
                "name":"cardListItem"
            },
            "navList":[
                {
                    "svg":"search",
                    "title":"自查记录",
                    "nav":"/pages/enforcement/more/MySearch",
                    "container":{
                        "background":"#F0E3B8"
                    }
                },
                {
                    "svg":"record",
                    "title":"执法记录",
                    "nav":"/pages/enforcement/more/companySearchDetail/companySearchDetail",
                    "container":{
                        "background":"#DDD5CA"
                    }
                },
                {
                    "svg":"data",
                    "title":"人员信息",
                    "nav":"/pages/enforcement/more/PeopleInformation",
                    "container":{
                        "background":"#9DB6D4"
                    }
                }
            ]
        }
    }
}
        

### 获取表单数据
GET {{endpoint}}/data?id=2004 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存表单数据
POST {{endpoint}}/data/2004 HTTP/1.1
content-type: application/json

{
    "name":"北京天翔文化产业有限公司",
    "people":"王伟伟",
    "address":"北京市海淀区文化产业园A8901",
    "date":"2020年3月1日",
    "phone":"13666000111",
    "certificates":[
        {"url":"","title":"营业执照"},
        {"url":"","title":"许可"}
    ],
    "scenePhoto":[
        {"url":"","title":""},
        {"url":"","title":""},
        {"url":"","title":""}
    ]
}