@endpoint = https://ai.hdqmjs.com

## 动态列表主页
# 跳转路由
# 前往各个子项
# 本页只提供路由跳转功能
### 获取列表主页数据
GET {{endpoint}}/form?id=2004
content-type: application/json


### 保存列表主页数据
POST {{endpoint}}/form/2004
content-type: application/json

{
    "version":"1",
    "name":"enforcementDetails",
    "title":"企业详情",
    "pageStyle":{
        "padding":"10px",
        "background":"#EFEFEF"
    },
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"autoform",
            "key":"autoform-7812-ad64-398a-451231561122",
            "name":"",
            "container":{
                "background":"white"
            }
        }
        //,
        //{
        //    "type":"navlist",
        //    "key":"navlists-7112-5154-2131-555256465455",
        //    "name":"更多",
        //    "container":{
        //        "grid-template-columns":"repeat(3, 33.33333333%)"
        //    }
        //}
    ],
    "moduleData":{
        "autoform-7812-ad64-398a-451231561122":{
            "loadApi":"https://ai.hdqmjs.com/api/u/companyInfo",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"企业信息",
                        "children": [{
                    "__config__": {
                    "label": "统一信用代码",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 101,
                    "renderKey": "1011625465993108"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "统一信用代码",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "licenceNo"
                    }, {
                    "__config__": {
                    "label": "公司名称",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 102,
                    "renderKey": "1021625466009609"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "公司名称",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "name"
                    }, {
                    "__config__": {
                    "label": "公司法人",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 104,
                    "renderKey": "1041625466167263"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "公司法人",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "personName"
                },
                                {
                    "__config__": {
                    "label": "企业经营负责人",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 108,
                    "renderKey": "1081635482606072"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入企业经营负责人",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "representativeName"
                },
                {
                    "__config__": {
                    "label": "企业负责人联系电话",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 109,
                    "renderKey": "1091628245404862"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "企业负责人联系电话",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "personPhone"
                },
                {
                    "__config__": {
                    "label": "公司地址",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 105,
                    "renderKey": "1051625466240303"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "公司地址",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "address"
                }, {
                    "__config__": {
                    "label": "注册资本",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 107,
                    "renderKey": "1071625466241039"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "注册资本",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "capital"
                }, {
                    "__config__": {
                    "label": "营业范围",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "textarea",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 106,
                    "renderKey": "1061625466240855"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "营业范围",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "businessScope"
                },{
                    "__config__": {
                    "label": "企业类型",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 110,
                    "renderKey": "1101628676663424"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "企业类型",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "companyType"
                }, {
                    "__config__": {
                    "label": "业务类型",
                    "showLabel": true,
                    "labelWidth": null,
                    "tag": "el-checkbox-group",
                    "tagIcon": "checkbox",
                    "layout": "colFormItem",
                    "span": 8,
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/checkbox",
                    "formId": 108,
                    "renderKey": "1081627530596290"
                    },
                    "__slot__": {
                        "options": [{
                            "label": "健身",
                            "value": "BBD"
                        }, {
                            "label": "游泳",
                            "value": "SW"
                        }, {
                            "label": "滑雪",
                            "value": "SKI"
                        }, {
                            "label": "潜水",
                            "value": "DIV"
                        }, {
                            "label": "攀岩",
                            "value": "RC"
                        }, {
                            "label": "滑冰",
                            "value": "SKA"
                        }, {
                            "label": "射箭",
                            "value": "ARC"
                        }, {
                            "label": "田径",
                            "value": "ATH"
                        }, {
                            "label": "羽毛球",
                            "value": "BAD"
                        }, {
                            "label": "皮划艇",
                            "value": "CAN"
                        }, {
                            "label": "棒球",
                            "value": "BASE"
                        }, {
                            "label": "篮球",
                            "value": "BASK"
                        }, {
                            "label": "拳击",
                            "value": "BOX"
                        }, {
                            "label": "自行车",
                            "value": "BIC"
                        }, {
                            "label": "击剑",
                            "value": "FEN"
                        }, {
                            "label": "足球",
                            "value": "FOOT"
                        }, {
                            "label": "手球",
                            "value": "HAND"
                        }, {
                            "label": "马术",
                            "value": "EQU"
                        }, {
                            "label": "曲棍球",
                            "value": "HOC"
                        }, {
                            "label": "柔道",
                            "value": "JUD"
                        }, {
                            "label": "现代五项",
                            "value": "MOD"
                        }, {
                            "label": "体操",
                            "value": "ART"
                        }, {
                            "label": "赛艇",
                            "value": "ROW"
                        }, {
                            "label": "帆船",
                            "value": "SAI"
                        }, {
                            "label": "射击",
                            "value": "SHO"
                        }, {
                            "label": "排球",
                            "value": "VOL"
                        }, {
                            "label": "垒球",
                            "value": "SOFT"
                        }, {
                            "label": "兵乒球",
                            "value": "BPP"
                        }, {
                            "label": "跆拳道",
                            "value": "TAE"
                        }, {
                            "label": "网球",
                            "value": "TEN"
                        }, {
                            "label": "铁人三项",
                            "value": "TRI"
                        }, {
                            "label": "举重",
                            "value": "WEI"
                        }, {
                            "label": "摔跤",
                            "value": "WRE"
                        }, {
                            "label": "冬季两项",
                            "value": "WIB"
                        }, {
                            "label": "冰壶",
                            "value": "CUR"
                        }, {
                            "label": "冰球",
                            "value": "ICH"
                        }, {
                            "label": "滑水",
                            "value": "SUR"
                        }, {
                            "label": "摩托艇",
                            "value": "MOT"
                        }, {
                            "label": "救生",
                            "value": "LIS"
                        }, {
                            "label": "健美操",
                            "value": "AER"
                        }, {
                            "label": "技巧",
                            "value": "SKL"
                        }, {
                            "label": "高尔夫球",
                            "value": "GOLF"
                        }, {
                            "label": "保龄球",
                            "value": "BOWL"
                        }, {
                            "label": "掷球",
                            "value": "THR"
                        }, {
                            "label": "台球",
                            "value": "BIL"
                        }, {
                            "label": "藤球",
                            "value": "SEP"
                        }, {
                            "label": "壁球",
                            "value": "SQU"
                        }, {
                            "label": "橄榄球",
                            "value": "RUG"
                        }, {
                            "label": "软式网球",
                            "value": "LTEN"
                        }, {
                            "label": "热气球",
                            "value": "HAB"
                        }, {
                            "label": "运动飞机",
                            "value": "SPAI"
                        }, {
                            "label": "跳伞",
                            "value": "SKDI"
                        }, {
                            "label": "滑翔",
                            "value": "GLID"
                        }, {
                            "label": "航空模型",
                            "value": "AVMO"
                        }, {
                            "label": "车辆模型",
                            "value": "VEMO"
                        }, {
                            "label": "航海模型",
                            "value": "NAMO"
                        }, {
                            "label": "定向",
                            "value": "DIR"
                        }, {
                            "label": "业余无线电",
                            "value": "AMR"
                        }, {
                            "label": "围棋",
                            "value": "TGOG"
                        }, {
                            "label": "国际象棋",
                            "value": "CHES"
                        }, {
                            "label": "中国象棋",
                            "value": "CCHE"
                        }, {
                            "label": "桥牌",
                            "value": "BRI"
                        }, {
                            "label": "武术",
                            "value": "AMA"
                        }, {
                            "label": "健身气功",
                            "value": "FIQG"
                        }, {
                            "label": "登山",
                            "value": "MOU"
                        }, {
                            "label": "汽车",
                            "value": "AUMO"
                        }, {
                            "label": "摩托车",
                            "value": "MOT"
                        }, {
                            "label": "轮滑",
                            "value": "ROSK"
                        }, {
                            "label": "毽球",
                            "value": "SHUT"
                        }, {
                            "label": "门球",
                            "value": "GATE"
                        }, {
                            "label": "舞龙舞狮",
                            "value": "DLDA"
                        }, {
                            "label": "龙舟",
                            "value": "DRBO"
                        }, {
                            "label": "钓鱼",
                            "value": "FISH"
                        }, {
                            "label": "风筝",
                            "value": "KITE"
                        }, {
                            "label": "信鸽",
                            "value": "CAPI"
                        }, {
                            "label": "体育舞蹈",
                            "value": "SPDA"
                        }, {
                            "label": "健美",
                            "value": "BOBU"
                        }, {
                            "label": "拔河",
                            "value": "TOW"
                        }, {
                            "label": "飞镖",
                            "value": "DART"
                        }, {
                            "label": "电子竞技",
                            "value": "ELSP"
                        }, {
                            "label":"蹦床",
                            "value":"TRA"
                        }, {
                            "label": "瑜伽",
                            "value": "YOG"
                        }]
                    },
                    "placeholder": "请选择类型",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "disabled": false,
                    "readonly":true,
                    "filterable": false,
                    "multiple": false,
                    "__vModel__": "type"
                }, {
                    "__config__": {
                    "label": "公司营业期限开始日期",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-date-picker",
                    "tagIcon": "date",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
                    "regList": [],
                    "formId": 109,
                    "renderKey": "1091625466317735"
                    },
                    "placeholder": "请输入公司营业期限开始日期",
                    "type": "date",
                    "style": {
                    "width": "100%"
                    },
                    "disabled": false,
                    "clearable": true,
                    "format": "yyyy-MM-dd",
                    "value-format": "yyyy-MM-dd",
                    "readonly": true,
                    "__vModel__": "startDate"
                },{
                    "__config__": {
                    "label": "公司营业期限终止日期",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-date-picker",
                    "tagIcon": "date",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
                    "regList": [],
                    "formId": 109,
                    "renderKey": "1091625466317735"
                    },
                    "placeholder": "公司营业期限终止日期",
                    "type": "date",
                    "style": {
                    "width": "100%"
                    },
                    "disabled": false,
                    "clearable": true,
                    "format": "yyyy-MM-dd",
                    "value-format": "yyyy-MM-dd",
                    "readonly": true,
                    "__vModel__": "expireDate"
                }, 
                {
                "__config__": {
                    "label": "企业负责人身份证号",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 109,
                    "renderKey": "1091628245404862"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入企业负责人身份证号",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "personIdNo"
                }, {
                    "__config__": {
                    "label": "法人身份证号",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 109,
                    "renderKey": "1091628245404862"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入法人身份证号",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "representativeIdNo"
                },
                {
                    "__config__": {
                    "label": "对外经营名称",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 114,
                    "renderKey": "1141634378082822"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入对外经营名称",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "operationName"
                },
                {
                    "__config__": {
                    "label": "实际经营地址",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 115,
                    "renderKey": "1151634378122719"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入实际经营地址",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "realOpAddress"
                },
                {
                    "__config__": {
                    "label": "紧急联系人",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 120,
                    "renderKey": "1201634973743671"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入紧急联系人",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "emeContactPerson"
                },
                {
                    "__config__": {
                    "label": "紧急联系电话",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 103,
                    "renderKey": "1031635219868403"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "请输入紧急企业负责人联系电话",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "emeContactPhone"
                },
                {
                    "__config__": {
                    "label": "地面/地下经营",
                    "showLabel": true,
                    "labelWidth": null,
                    "tag": "el-select",
                    "tagIcon": "select",
                    "layout": "colFormItem",
                    "span": 8,
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/select",
                    "formId": 118,
                    "renderKey": "1181634378327331",
                    "defaultValue": ""
                    },
                    "__slot__": {
                    "options": [{
                        "label": "地面经营",
                        "value": "ground"
                    }, {
                        "label": "地下经营",
                        "value": "underground"
                    }, {
                        "label": "地面及地下经营",
                        "value": "groundAndUnder"
                    }]
                    },
                    "placeholder": "请选择地面/地下经营",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "disabled": false,
                    "readonly":true,
                    "filterable": false,
                    "multiple": false,
                    "__vModel__": "operationPlace"
                },
                {
                    "__config__": {
                    "label": "面积",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 103,
                    "renderKey": "1031639234248177"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "面积（建筑面积）",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "area"
                }, {
                    "__config__": {
                    "label": "水域面积",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "el-input",
                    "tagIcon": "input",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/input",
                    "regList": [],
                    "formId": 104,
                    "renderKey": "1041639234283614"
                    },
                    "__slot__": {
                    "prepend": "",
                    "append": ""
                    },
                    "placeholder": "游泳类企业需要填入水域面积",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "prefix-icon": "",
                    "suffix-icon": "",
                    "maxlength": null,
                    "show-word-limit": false,
                    "readonly": true,
                    "hidden": false,
                    "disabled": false,
                    "__vModel__": "waterArea"
                },{
                    "__config__": {
                    "label": "培训对象",
                    "showLabel": true,
                    "labelWidth": null,
                    "tag": "el-select",
                    "tagIcon": "select",
                    "layout": "colFormItem",
                    "span": 8,
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/select",
                    "formId": 106,
                    "renderKey": "1061639290090237"
                    },
                    "__expect__": {
                    "field": "isTrain",
                    "value": true
                    },
                    "__slot__": {
                    "options": [{
                        "label": "成人及儿童",
                        "value": "3"
                    }, {
                        "label": "儿童",
                        "value": "1"
                    }, {
                        "label": "成人",
                        "value": "2"
                    }]
                    },
                    "placeholder": "请选择培训对象",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "disabled": false,
                    "filterable": false,
                    "multiple": false,
                    "readonly": true,
                    "__vModel__": "trainingObject"
                }, {
                    "__config__": {
                    "label": "培训类型",
                    "showLabel": true,
                    "labelWidth": null,
                    "tag": "el-checkbox-group",
                    "tagIcon": "checkbox",
                    "layout": "colFormItem",
                    "span": 8,
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/checkbox",
                    "formId": 107,
                    "renderKey": "1071639290181085"
                    },
                    "__slot__": {
                    "options": [{
                        "label": "健身",
                        "value": "BBD"
                    }, {
                        "label": "游泳",
                        "value": "SW"
                    }, {
                        "label": "滑雪",
                        "value": "SKI"
                    }, {
                        "label": "潜水",
                        "value": "DIV"
                    }, {
                        "label": "攀岩",
                        "value": "RC"
                    }, {
                        "label": "滑冰",
                        "value": "SKA"
                    }, {
                        "label": "射箭",
                        "value": "ARC"
                    }, {
                        "label": "田径",
                        "value": "ATH"
                    }, {
                        "label": "羽毛球",
                        "value": "BAD"
                    }, {
                        "label": "皮划艇",
                        "value": "CAN"
                    }, {
                        "label": "棒球",
                        "value": "BASE"
                    }, {
                        "label": "篮球",
                        "value": "BASK"
                    }, {
                        "label": "拳击",
                        "value": "BOX"
                    }, {
                        "label": "自行车",
                        "value": "BIC"
                    }, {
                        "label": "击剑",
                        "value": "FEN"
                    }, {
                        "label": "足球",
                        "value": "FOOT"
                    }, {
                        "label": "手球",
                        "value": "HAND"
                    }, {
                        "label": "马术",
                        "value": "EQU"
                    }, {
                        "label": "曲棍球",
                        "value": "HOC"
                    }, {
                        "label": "柔道",
                        "value": "JUD"
                    }, {
                        "label": "现代五项",
                        "value": "MOD"
                    }, {
                        "label": "体操",
                        "value": "ART"
                    }, {
                        "label": "赛艇",
                        "value": "ROW"
                    }, {
                        "label": "帆船",
                        "value": "SAI"
                    }, {
                        "label": "射击",
                        "value": "SHO"
                    }, {
                        "label": "排球",
                        "value": "VOL"
                    }, {
                        "label": "垒球",
                        "value": "SOFT"
                    }, {
                        "label": "兵乒球",
                        "value": "BPP"
                    }, {
                        "label": "跆拳道",
                        "value": "TAE"
                    }, {
                        "label": "网球",
                        "value": "TEN"
                    }, {
                        "label": "铁人三项",
                        "value": "TRI"
                    }, {
                        "label": "举重",
                        "value": "WEI"
                    }, {
                        "label": "摔跤",
                        "value": "WRE"
                    }, {
                        "label": "冬季两项",
                        "value": "WIB"
                    }, {
                        "label": "冰壶",
                        "value": "CUR"
                    }, {
                        "label": "冰球",
                        "value": "ICH"
                    }, {
                        "label": "滑水",
                        "value": "SUR"
                    }, {
                        "label": "摩托艇",
                        "value": "MOT"
                    }, {
                        "label": "救生",
                        "value": "LIS"
                    }, {
                        "label": "健美操",
                        "value": "AER"
                    }, {
                        "label": "技巧",
                        "value": "SKL"
                    }, {
                        "label": "高尔夫球",
                        "value": "GOLF"
                    }, {
                        "label": "保龄球",
                        "value": "BOWL"
                    }, {
                        "label": "掷球",
                        "value": "THR"
                    }, {
                        "label": "台球",
                        "value": "BIL"
                    }, {
                        "label": "藤球",
                        "value": "SEP"
                    }, {
                        "label": "壁球",
                        "value": "SQU"
                    }, {
                        "label": "橄榄球",
                        "value": "RUG"
                    }, {
                        "label": "软式网球",
                        "value": "LTEN"
                    }, {
                        "label": "热气球",
                        "value": "HAB"
                    }, {
                        "label": "运动飞机",
                        "value": "SPAI"
                    }, {
                        "label": "跳伞",
                        "value": "SKDI"
                    }, {
                        "label": "滑翔",
                        "value": "GLID"
                    }, {
                        "label": "航空模型",
                        "value": "AVMO"
                    }, {
                        "label": "车辆模型",
                        "value": "VEMO"
                    }, {
                        "label": "航海模型",
                        "value": "NAMO"
                    }, {
                        "label": "定向",
                        "value": "DIR"
                    }, {
                        "label": "业余无线电",
                        "value": "AMR"
                    }, {
                        "label": "围棋",
                        "value": "TGOG"
                    }, {
                        "label": "国际象棋",
                        "value": "CHES"
                    }, {
                        "label": "中国象棋",
                        "value": "CCHE"
                    }, {
                        "label": "桥牌",
                        "value": "BRI"
                    }, {
                        "label": "武术",
                        "value": "AMA"
                    }, {
                        "label": "健身气功",
                        "value": "FIQG"
                    }, {
                        "label": "登山",
                        "value": "MOU"
                    }, {
                        "label": "汽车",
                        "value": "AUMO"
                    }, {
                        "label": "摩托车",
                        "value": "MOT"
                    }, {
                        "label": "轮滑",
                        "value": "ROSK"
                    }, {
                        "label": "毽球",
                        "value": "SHUT"
                    }, {
                        "label": "门球",
                        "value": "GATE"
                    }, {
                        "label": "舞龙舞狮",
                        "value": "DLDA"
                    }, {
                        "label": "龙舟",
                        "value": "DRBO"
                    }, {
                        "label": "钓鱼",
                        "value": "FISH"
                    }, {
                        "label": "风筝",
                        "value": "KITE"
                    }, {
                        "label": "信鸽",
                        "value": "CAPI"
                    }, {
                        "label": "体育舞蹈",
                        "value": "SPDA"
                    }, {
                        "label": "健美",
                        "value": "BOBU"
                    }, {
                        "label": "拔河",
                        "value": "TOW"
                    }, {
                        "label": "飞镖",
                        "value": "DART"
                    }, {
                        "label": "电子竞技",
                        "value": "ELSP"
                    }, {
                        "label": "蹦床",
                        "value": "TRA"
                    }, {
                        "label": "瑜伽",
                        "value": "YOG"
                    }]
                    },
                    "__expect__": {
                    "field": "isTrain",
                    "value": true
                    },
                    "placeholder": "请选择培训类型",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "disabled": false,
                    "filterable": false,
                    "readonly": true,
                    "multiple": false,
                    "__vModel__": "trainingType"
                },
                {
                    "__config__": {
                    "label": "所在街镇",
                    "showLabel": true,
                    "labelWidth": null,
                    "tag": "c-select-street",
                    "tagIcon": "select",
                    "layout": "colFormItem",
                    "span": 8,
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/select",
                    "formId": 104,
                    "renderKey": "1041628235895717"
                    },
                    "placeholder": "所在街镇",
                    "style": {
                    "width": "100%"
                    },
                    "clearable": true,
                    "disabled": true,
                    "filterable": false,
                    "multiple": false,
                    "loadApi": "https://ai.hdqmjs.com/admin/dept/street-tree",
                    "response": "data",
                    "__vModel__": "streetId"
                },
                {
                    "__config__": {
                    "label": "高危证书到期时间",
                    "tag": "el-date-picker",
                    "tagIcon": "date",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "span": 8,
                    "layout": "colFormItem",
                    "required": false,
                    "regList": [],
                    "changeTag": true,
                    "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
                    "formId": 114,
                    "renderKey": "1141640967289618"
                    },
                    "placeholder": "请选择高危证书到期时间",
                    "type": "date",
                    "style": {
                    "width": "100%"
                    },
                    "disabled": false,
                    "clearable": true,
                    "format": "yyyy-MM-dd",
                    "value-format": "yyyy-MM-dd",
                    "readonly": true,
                    "__vModel__": "dangerousCertDate"
                }, {
                    "__config__": {
                    "label": "高危证书文件",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 8,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 115,
                    "renderKey": "1151640967337636"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "readonly":true,
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "text",
                    "multiple": false,
                    "__vModel__": "dangerousCertFilesUrl"
                },
                {
                    "__config__": {
                    "label": "营业执照图片",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 24,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 101,
                    "renderKey": "1011639294446695"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "picture",
                    "readonly":"true",
                    "multiple": false,
                    "__vModel__": "licenceImagesUrl"
                }, {
                    "__config__": {
                    "label": "房屋所有权证",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 24,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 102,
                    "renderKey": "1021639294447396"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "picture",
                    "multiple": false,
                    "readonly":"true",
                    "__vModel__": "houseOwershipImagesUrl"
                }, {
                    "__config__": {
                    "label": "制度文件",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 24,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 103,
                    "renderKey": "1031639294447795"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "picture",
                    "multiple": false,
                    "readonly":"true",
                    "__vModel__": "safetyRegulationFilesUrl"
                }, {
                    "__config__": {
                    "label": "场馆图片",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 24,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 104,
                    "renderKey": "1041639294586774"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "text",
                    "multiple": false,
                    "readonly":"true",
                    "__vModel__": "sceneImagesUrl"
                }, {
                    "__config__": {
                    "label": "员工资质信息",
                    "tag": "el-upload",
                    "tagIcon": "upload",
                    "layout": "colFormItem",
                    "defaultValue": null,
                    "showLabel": true,
                    "labelWidth": null,
                    "required": false,
                    "span": 24,
                    "showTip": false,
                    "buttonText": "点击上传",
                    "regList": [],
                    "changeTag": true,
                    "fileSize": 2,
                    "sizeUnit": "MB",
                    "document": "https://element.eleme.cn/#/zh-CN/component/upload",
                    "formId": 105,
                    "renderKey": "1051639294587202"
                    },
                    "__slot__": {
                    "list-type": true
                    },
                    "action": "https://jsonplaceholder.typicode.com/posts/",
                    "disabled": false,
                    "accept": "",
                    "name": "file",
                    "auto-upload": true,
                    "list-type": "text",
                    "multiple": false,
                    "readonly":"true",
                    "__vModel__": "staffQualificationImagesUrl"
                },
                {
                    "__config__": {
                    "label": "地图位置",
                    "labelWidth": null,
                    "showLabel": true,
                    "changeTag": true,
                    "tag": "c-map-mes",
                    "tagIcon": "map",
                    "required": false,
                    "layout": "colFormItem",
                    "span": 8,
                    "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
                    "regList": [],
                    "formId": 108,
                    "renderKey": "1081625466287648"
                    },
                    "placeholder": "地图位置",
                    "type": "map",
                    "style": {
                    "width": "100%"
                    },
                    "disabled": true,
                    "clearable": true,
                    "readonly": false,
                    "__vModel__": "map"
                }]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "navlists-7112-5154-2131-555256465455":{
            "itemModule":{
                "name":"cardListItem"
            },
            "navList":[
                {
                    "svg":"search",
                    "title":"自查记录",
                    "nav":"/pages/enforcement/more/MySearch",
                    "container":{
                        "background":"#F0E3B8"
                    }
                },
                {
                    "svg":"record",
                    "title":"执法记录",
                    "nav":"/pages/enforcement/more/companySearchDetail/companySearchDetail",
                    "container":{
                        "background":"#DDD5CA"
                    }
                },
                {
                    "svg":"data",
                    "title":"人员信息",
                    "nav":"/pages/enforcement/more/PeopleInformation",
                    "container":{
                        "background":"#9DB6D4"
                    }
                }
            ]
        }
    }
}
        

### 获取表单数据
GET {{endpoint}}/data?id=2004 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存表单数据
POST {{endpoint}}/data/2004 HTTP/1.1
content-type: application/json

{
    "name":"北京天翔文化产业有限公司",
    "people":"王伟伟",
    "address":"北京市海淀区文化产业园A8901",
    "date":"2020年3月1日",
    "phone":"13666000111",
    "certificates":[
        {"url":"","title":"营业执照"},
        {"url":"","title":"许可"}
    ],
    "scenePhoto":[
        {"url":"","title":""},
        {"url":"","title":""},
        {"url":"","title":""}
    ]
}