@endpoint=https://ai.hdqmjs.com

## 整改复查 

### 获取整改复查页面数据 
GET {{endpoint}}/form?id=3000


### 保存整改复查页面数据
POST {{endpoint}}/form/3000
content-type: application/json

{  
    "version": "1",
    "name": "my_enforcement",
    "title": "整改复查",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type":"autolist",
        "name":"",
        "key":"46412315-8775-1545-5646-8711645452154"
      }
    ],
    "moduleData": {
         "46412315-8775-1545-5646-8711645452154": {
            "loadApi":"https://ai.hdqmjs.com/api.flow.process/instanceListPage",
            "method":"POST",
            "itemNavigation": "/enforcement/book/moreBook?piId",
            "response":{
                "list":"list"
            },
            "request":{
                "default":{
                  "formType": "zg"
                },
                "fileno":"fileno",
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "options":{
              "noSuccess":"待确认",
              "success":"已整改",
              "wait":"待反馈"
            },
            "itemModule":{
                "type":"custom_component",
                "name":"company-state-to-enforcement"
            }
         }
    }
}
