@endpoint=https://ai.hdqmjs.com

## 新首页(第三方接口)

### 获取数据新首页 
GET {{endpoint}}/form?id=888


### 新首页
POST {{endpoint}}/form/888
content-type: application/json

{  
    "version": "1",
    "name": "loginPage",
    "title": "智慧执法",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type":"banner",
        "name":"",
        "key":"89084045-v4d5-7122-3300-1623511112885"
      },
      {
        "type":"navlist",
        "name":"请选择用户角色绑定登录",
        "key":"d4a555sd-hf22-qqds-8412-16234da445885",
        "container":{
                "grid-template-columns":"repeat(2, 50%)"
            }
      }
    ],
    "moduleData": {
        "89084045-v4d5-7122-3300-1623511112885": {
            "banners": [
                {
                    "img": "https://ai.hdqmjs.com/attachments/banner/banner.png",
                    "itemNavigation": "/?id=1"
                }
            ]
        },
        "d4a555sd-hf22-qqds-8412-16234da445885": {
            "itemModule":{
              "name":"subTitleCardItem"
           },
            "navList": [
                {
                    "svg":"navEnf",
                    //"svg":"enforcement",
                    "title":"执法用户",
                    "subTitle":"执法工作人员绑定",
                    "nav":"/pages/login/third-Login/IsLogin?id=2",
                    "container":{
                    }
                },
                {
                    "svg":"navCompany",
                    //"svg":"enterprise",
                    "title":"企业用户",
                    "subTitle":"企业用户绑定",
                    "nav":"/pages/login/third-Login/IsLogin?id=4",
                    "container":{
                    }
                },
                {
                    "svg":"navStre",
                    //"svg":"street",
                    "title":"街镇用户",
                    "subTitle":"街镇用户上报绑定",
                    "nav":"/pages/login/third-Login/IsLogin?id=3",
                    "container":{
                    }
                },
                {
                    "svg":"inputCompany",
                    //"img":"https://ai.hdqmjs.com/attachments/input/company.png",
                    "title":"企业信息库",
                    "subTitle":"企业信息添加申请",
                    "nav":"/pages/login/addCompany",
                    "container":{
                    }
                },
                {
                    "svg":"record",
                    //"img":"https://ai.hdqmjs.com/attachments/input/company.png",
                    "title":"操作手册",
                    "subTitle":"企业用户操作手册",
                    "nav":"/pages/NoticeDetail?id=28",
                    "container":{
                    }
                }
            ]
        }
    }
}
