@endpoint = https://ai.hdqmjs.com
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI1LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjIwNiwiaG91ciI6MTEsIm1pbnV0ZSI6MTEsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjEyMTAwMDAwMCwic2Vjb25kIjoxLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiJjNWZiMzFlODRhNzg0Mzk5OWNkNjc0NmRkMGZmNGQwNSIsInJlZnJlc2hfdG9rZW4iOiI5ZjM2NTFhZjg5ODg0ZWIxODczODI1OTBjMDExYTFmMyIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6NzMsInVzZXJuYW1lIjoiMmM1MzA0MTgxOWQ0NDE4OTgwNDQ3MTcwM2VmN2FhMzMiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjoyLCJ0aW1lX3N0YW1wIjoiMTYyNjMxODY2MSIsInJvbGVfY29kZXMiOlsiQVNTIl0sIm5pY2tuYW1lIjoi5b6u5L-h55So5oi3In0.BHOzzleEMfndh3yp2m-Bi6If86UHvPuKhD3SrNXabKw
@token2 = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjMwLCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjIxMSwiaG91ciI6MTMsIm1pbnV0ZSI6NTAsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjQ3NjAwMDAwMCwic2Vjb25kIjoxLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiJkMTRmMDc2MTM1NGU0ZWI3YTc2NDg0MjYwMjE3OGI4ZiIsInJlZnJlc2hfdG9rZW4iOiIzNGIxMTRjN2Q4ZmE0ZjA4OTBjNzYwMDA5YjAwNzc5NyIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MSwiZGVwdF9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI2NzYwMjAxIiwicm9sZV9jb2RlcyI6WyJST0xFX0FETUlOIl0sIm5pY2tuYW1lIjoi6LaF57qn566h55CG5ZGYIn0._WGWxs60gOCVfyLQ6PuQcWRJXIvYc4sYVBIfrPnNUcA
@username = 2c53041819d44189804471703ef7aa33
@username1 = ""
GET {{endpoint}}/admin/user/info/{{username}}
Authorization: Bearer {{token2}}
###
GET {{endpoint}}/admin/user/Info
Authorization: Bearer {{token2}}

### 绑定用户
POST {{endpoint}}/admin/appuser/bindUser
Content-Type: application/x-www-form-urlencoded


&app=internal
&auth=001epIkl2f1so74KyRkl2JGEZy2epIkA
&from=2
&password=123456
&type=2
&username=testuser10086

@id = 1415599514978365441

@tokenadmin=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI1LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjIwNiwiaG91ciI6MTQsIm1pbnV0ZSI6NDIsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjgzNDAwMDAwMCwic2Vjb25kIjoyMiwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiJkNjJhYzMwMGVkY2M0MTRmOTNmZGI0YzBhYjVkYjgyZSIsInJlZnJlc2hfdG9rZW4iOiJjNjkyNGI5MjE3MzY0M2Q0OTE2OGYwMjA2N2NiOWFlYiIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MSwiZGVwdF9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI2MzMxMzQyIiwicm9sZV9jb2RlcyI6WyJST0xFX0FETUlOIl0sIm5pY2tuYW1lIjoi6LaF57qn566h55CG5ZGYIn0.lp4Ei03WtW8OI-A2L5pT6i9I9JqAjBrZVc0WI5cNLVY
@token2 = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI1LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjIwNiwiaG91ciI6MTYsIm1pbnV0ZSI6MzksIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjM4OTAwMDAwMCwic2Vjb25kIjozLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiJlNGJjMmEyMzAwZWM0YWU1ODhmZWEzYTNkMzE0NDhhOSIsInJlZnJlc2hfdG9rZW4iOiI3OWJjZTkyNmJlYWU0ZGIyOGM5NjdjNWNiZWRiYmY5OSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MSwiZGVwdF9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI2MzM4MzQzIiwicm9sZV9jb2RlcyI6WyJST0xFX0FETUlOIl0sIm5pY2tuYW1lIjoi6LaF57qn566h55CG5ZGYIn0.wdyEojQl7K_QxlLz5GzjiywatXXm4Qxj8d6JQPBITnA
@01token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI1LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjIwNiwiaG91ciI6MTYsIm1pbnV0ZSI6NTksIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjQwOTAwMDAwMCwic2Vjb25kIjozMiwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiI4ZTQ1ZWE4NmZiZTU0NjdlOTIzYzBhN2QxNGEwMWM5MiIsInJlZnJlc2hfdG9rZW4iOiI5NmM2YTEyYWRkNTY0NzcwYWRiMmJmMDU0NDg1YWJlZCIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6NywiZGVwdF9pZCI6OSwidXNlcm5hbWUiOiIwMDAwMDEiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjowLCJ0aW1lX3N0YW1wIjoiMTYyNjMzOTU3MiIsInJvbGVfY29kZXMiOlsiUk9MRV9BRE1JTiJdfQ.H8yyk3fNyQcB0-ZQArT9GPLrxwvgjFnoHFBEgUJple4
@ntoken = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI1LCJkYXlPZldlZWsiOiJTVU5EQVkiLCJkYXlPZlllYXIiOjIwNiwiaG91ciI6MTYsIm1pbnV0ZSI6MzksIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjM4OTAwMDAwMCwic2Vjb25kIjozLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiJlNGJjMmEyMzAwZWM0YWU1ODhmZWEzYTNkMzE0NDhhOSIsInJlZnJlc2hfdG9rZW4iOiI3OWJjZTkyNmJlYWU0ZGIyOGM5NjdjNWNiZWRiYmY5OSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MSwiZGVwdF9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI2MzM4MzQzIiwicm9sZV9jb2RlcyI6WyJST0xFX0FETUlOIl0sIm5pY2tuYW1lIjoi6LaF57qn566h55CG5ZGYIn0.wdyEojQl7K_QxlLz5GzjiywatXXm4Qxj8d6JQPBITnA
###
DELETE https://rt.zbsoft.top/admin/systhirdpartyuser/{{id}}
Authorization: Bearer {{token2}}

###
GET https://rt.zbsoft.top/admin/systhirdpartyuser/1409700014225154050
Authorization: Bearer {{token2}}


###
GET https://rt.zbsoft.top/admin/user/page
Authorization: Bearer {{token2}}

###获取所有用户信息
GET https://rt.zbsoft.top/admin/systhirdpartyuser/page?size=22
Authorization: Bearer {{token2}}
Content-Type: application/json

{
    "size":21
}

###
PUT https://rt.zbsoft.top/admin/systhirdpartyuser/
Authorization: Bearer {{token2}}
Content-Type: application/json

{
"id": "1415599514978365441",
"userId": "",
"from": 2,
"openId": "",
"unionId": null,
"imageUrl": "https://thirdwx.qlogo.cn/mmopen/vi_32/uB6Rprr8UiawFHIiblIPk4ZyNMdgJ2kjCC7FLjQibyl6ibHAh7qnJgIYBzLE5uqsoricVxAMV72G6iakyftp4cy6ibvWA/132",
"nickname": "AEdge",
"gender": 1,
"country": "China",
"province": "Guangdong",
"city": "Shantou",
"createTime": "2021-07-15 17:10:00",
"updateTime": "2021-07-16 11:16:02",
"app": "internal"
}

###
@tk = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjMwLCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjIxMSwiaG91ciI6MTMsIm1pbnV0ZSI6NTMsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjcxODAwMDAwMCwic2Vjb25kIjoyOCwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiIyYmUwNTBlYzA3MDY0Y2JmODRhMTVhMzMyYTM3YTBmYyIsInJlZnJlc2hfdG9rZW4iOiIzNmI1ZGQxNGY4ZmI0NmMxOTEyOWM1OGJjNzExYWI3OSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MTMyLCJkZXB0X2lkIjo3LCJ1c2VybmFtZSI6InpmcnkwMTAiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjoyLCJ0aW1lX3N0YW1wIjoiMTYyNjc2MDQwOCIsInJvbGVfY29kZXMiOlsiQVNTIl19.81nj7LIflRJiXzQWlapeUw4JJxnkmm8TYXF6RaFP7-Q
GET https://rt.zbsoft.top/auth/token/logout/
Authorization: Bearer {{tk}}

