@endpoint=https://ai.hdqmjs.com



###
GET {{endpoint}}/form?id=1

###
POST {{endpoint}}/form/1
Content-Type: application/json

{
    "globalConfig": {
      "useCache": false,
      "endpoint": "https://ai.hdqmjs.com",
      "authEP": "https://ai.hdqmjs.com",
      "designEP": "https://ai.hdqmjs.com",
      "formEP": "https://ai.hdqmjs.com/form",
      "workflowEP": "https://ai.hdqmjs.com",
      "dataEP": "https://ai.hdqmjs.com/data",
      "extraEP": "https://ai.hdqmjs.com",
      "loginEP":"https://ai.hdqmjs.com",
      "YyzzEP":"https://ai.hdqmjs.com"
    }
}
### 图标存放地址 http://ai.hdqmjs.com
### /root/ai.hdqmjs.com/sports-api/api/attachments
### 获取图标数据
GET {{endpoint}}/data?id=9999999 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存图标地址数据
POST {{endpoint}}/data/9999999 HTTP/1.1
content-type: application/json

{
    "search":"https://ai.hdqmjs.com/attachments/public/search-blue.png",
    "setting":"https://ai.hdqmjs.com/attachments/public/setting.png",
    "file":"https://ai.hdqmjs.com/attachments/public/file.png",
    "report":"https://ai.hdqmjs.com/attachments/public/report.png",
    "listZc":"https://ai.hdqmjs.com/attachments/list/listZc.png",
    "listZf":"https://ai.hdqmjs.com/attachments/list/listZf.png",
    "listGgqyxx":"https://ai.hdqmjs.com/attachments/list/listGgqyxx.png",
    "listFg":"https://ai.hdqmjs.com/attachments/list/listFg.png",
    "MapCompany":"https://ai.hdqmjs.com/attachments/map/MapCompany.png",
    "MapMy":"https://ai.hdqmjs.com/attachments/map/MapMy.png",
    "MapSuccess":"https://ai.hdqmjs.com/attachments/map/MapSuccess.png",
    "buttonCf":"https://ai.hdqmjs.com/attachments/button/ButtonCf.png",
    "buttonZg":"https://ai.hdqmjs.com/attachments/button/ButtonZg.png",
    "empty":"https://ai.hdqmjs.com/attachments/public/empty.png",
    "navReSetting":"https://ai.hdqmjs.com/attachments/Company/reSetting.png",
    "navReturnWork":"https://ai.hdqmjs.com/attachments/Company/ReturnWork.png",
    "navSelfSearch":"https://ai.hdqmjs.com/attachments/Company/selfSearch.png",
    "typeZc":"https://ai.hdqmjs.com/attachments/enforcement/type/zc.png",
    "typeTest":"https://ai.hdqmjs.com/attachments/enforcement/type/test.png",
    "typeZglc":"https://ai.hdqmjs.com/attachments/enforcement/type/zglc.png",
    "typeCf":"https://ai.hdqmjs.com/attachments/enforcement/type/cf.png",
    "typeZg":"https://ai.hdqmjs.com/attachments/enforcement/type/zg.png",
    "typeJdsb":"https://ai.hdqmjs.com/attachments/enforcement/type/jdsb.png",
    "typeXzxk":"https://ai.hdqmjs.com/attachments/enforcement/type/xzxk.png",
    "typeZflc":"https://ai.hdqmjs.com/attachments/enforcement/type/zflc.png",
    "typeZf":"https://ai.hdqmjs.com/attachments/enforcement/type/zflc.png",
    "typeFg":"https://ai.hdqmjs.com/attachments/enforcement/type/fg.png",
    "typeYyzz":"https://ai.hdqmjs.com/attachments/enforcement/type/yyzz.png",
    "inputEnforcement":"https://ai.hdqmjs.com/attachments/input/enforcement.png",
    "inputCompany":"https://ai.hdqmjs.com/attachments/input/company.png",
    "inputStreet":"https://ai.hdqmjs.com/attachments/input/street.png",
    "inputPassword":"https://ai.hdqmjs.com/attachments/input/password.png",
    "inputPhone":"https://ai.hdqmjs.com/attachments/input/phone.png",
    "tabbarMy":"https://ai.hdqmjs.com/attachments/tabbar/my.png",
    "tabbarMyActive":"https://ai.hdqmjs.com/attachments/tabbar/my-active.png",
    "tabbarPolicy":"https://ai.hdqmjs.com/attachments/tabbar/policy.png",
    "tabbarPolicyActive":"https://ai.hdqmjs.com/attachments/tabbar/policy-active.png",
    "tabbarEnforcement":"https://ai.hdqmjs.com/attachments/tabbar/enforcement.png",
    "tabbarEnforcementActive":"https://ai.hdqmjs.com/attachments/tabbar/enforcement-active.png",
    "tabbarCompanyData":"https://ai.hdqmjs.com/attachments/tabbar/CompanyData.png",
    "tabbarCompanyDataActive":"https://ai.hdqmjs.com/attachments/tabbar/CompanyData-active.png",
    "avatarMy":"https://ai.hdqmjs.com/attachments/Avatar/myAvatar.png",
    "arrowRight":"https://ai.hdqmjs.com/attachments/arrow/right.png",
    "select":"https://ai.hdqmjs.com/attachments/public/list-select.png",
    "record":"https://ai.hdqmjs.com/attachments/public/record.png",
    "street":"https://ai.hdqmjs.com/attachments/public/street.png",
    "picture":"https://ai.hdqmjs.com/attachments/public/picture.png",
    "notice":"https://ai.hdqmjs.com/attachments/public/notice.png",
    "typeZf001":"https://ai.hdqmjs.com/attachments/nav/publicity.png",
    "typeZf002":"https://ai.hdqmjs.com/attachments/nav/adminLicence.png",
    "typeZf003":"https://ai.hdqmjs.com/attachments/nav/lifeguard.png",
    "typeZf004":"https://ai.hdqmjs.com/attachments/nav/licence.png",
    "typeZf005":"https://ai.hdqmjs.com/attachments/nav/employees.png",
    "typeZf006":"https://ai.hdqmjs.com/attachments/nav/export.png",
    "typeZf007":"https://ai.hdqmjs.com/attachments/nav/warning.png",
    "typeZf008":"https://ai.hdqmjs.com/attachments/nav/instructions.png",
    "typeZf009":"https://ai.hdqmjs.com/attachments/nav/radio.png",
    "typeZf010":"https://ai.hdqmjs.com/attachments/nav/rules.png",
    "typeZf011":"https://ai.hdqmjs.com/attachments/nav/drill.png",
    "typeZf012":"https://ai.hdqmjs.com/attachments/nav/cpdx.png",
    "typeZf013":"https://ai.hdqmjs.com/attachments/nav/wcnrcp.png",
    "typeZf014":"https://ai.hdqmjs.com/attachments/nav/dxcf.png",
    "typeZf015":"https://ai.hdqmjs.com/attachments/nav/xy.png",
    "typeZf016":"https://ai.hdqmjs.com/attachments/nav/wg.png",
    "typeZf017":"https://ai.hdqmjs.com/attachments/nav/byz.png",
    "typeZf018":"https://ai.hdqmjs.com/attachments/nav/cp.png",
    "typeZf019":"https://ai.hdqmjs.com/attachments/nav/qfqy.png",
    "typeZf020":"https://ai.hdqmjs.com/attachments/nav/ch.png",
    "typeZf021":"https://ai.hdqmjs.com/attachments/enforcement/type/cf.png",
    "typeZf022":"https://ai.hdqmjs.com/attachments/nav/sb.png",

    "typeZf001_xx":"https://ai.hdqmjs.com/attachments/nav/publicity.png",
    "typeZf002_xx":"https://ai.hdqmjs.com/attachments/nav/adminLicence.png",
    "typeZf003_xx":"https://ai.hdqmjs.com/attachments/nav/lifeguard.png",
    "typeZf004_xx":"https://ai.hdqmjs.com/attachments/nav/licence.png",
    "typeZf005_xx":"https://ai.hdqmjs.com/attachments/nav/employees.png",
    "typeZf006_xx":"https://ai.hdqmjs.com/attachments/nav/export.png",
    "typeZf007_xx":"https://ai.hdqmjs.com/attachments/nav/warning.png",
    "typeZf008_xx":"https://ai.hdqmjs.com/attachments/nav/instructions.png",
    "typeZf009_xx":"https://ai.hdqmjs.com/attachments/nav/radio.png",
    "typeZf010_xx":"https://ai.hdqmjs.com/attachments/nav/rules.png",
    "typeZf011_xx":"https://ai.hdqmjs.com/attachments/nav/drill.png",
    "typeZf012_xx":"https://ai.hdqmjs.com/attachments/nav/cpdx.png",
    "typeZf013_xx":"https://ai.hdqmjs.com/attachments/nav/wcnrcp.png",
    "typeZf014_xx":"https://ai.hdqmjs.com/attachments/nav/dxcf.png",
    "typeZf015_xx":"https://ai.hdqmjs.com/attachments/nav/xy.png",
    "typeZf016_xx":"https://ai.hdqmjs.com/attachments/nav/wg.png",
    "typeZf017_xx":"https://ai.hdqmjs.com/attachments/nav/byz.png",
    "typeZf018_xx":"https://ai.hdqmjs.com/attachments/nav/cp.png",
    "typeZf019_xx":"https://ai.hdqmjs.com/attachments/nav/qfqy.png",
    "typeZf020_xx":"https://ai.hdqmjs.com/attachments/nav/ch.png",
    "typeZf021_xx":"https://ai.hdqmjs.com/attachments/enforcement/type/cf.png",
    "typeZf022_xx":"https://ai.hdqmjs.com/attachments/nav/sb.png",

    "typeZg001":"https://ai.hdqmjs.com/attachments/nav/nosafe.png",
    "typeZg002":"https://ai.hdqmjs.com/attachments/nav/nosafe.png",
    "typeZg003":"https://ai.hdqmjs.com/attachments/nav/noRule.png",
    "typeZg004":"https://ai.hdqmjs.com/attachments/nav/noRule.png",
    "typeZg005":"https://ai.hdqmjs.com/attachments/nav/nolife.png",
    "typeZg006":"https://ai.hdqmjs.com/attachments/nav/nolife.png",
    "typeZg007":"https://ai.hdqmjs.com/attachments/nav/noLicense.png",
    "typeZg008":"https://ai.hdqmjs.com/attachments/nav/noLicense.png",
    "typeZg009":"https://ai.hdqmjs.com/attachments/nav/nolanguage.png",
    "typeZg010":"https://ai.hdqmjs.com/attachments/nav/nolanguage.png",
    "typeCf001":"https://ai.hdqmjs.com/attachments/nav/nosafe.png",
    "typeCf002":"https://ai.hdqmjs.com/attachments/nav/nosafe.png",
    "typeCf003":"https://ai.hdqmjs.com/attachments/nav/noRule.png",
    "typeCf004":"https://ai.hdqmjs.com/attachments/nav/noRule.png",
    "typeCf005":"https://ai.hdqmjs.com/attachments/nav/nolife.png",
    "typeCf006":"https://ai.hdqmjs.com/attachments/nav/nolife.png",
    "typeCf007":"https://ai.hdqmjs.com/attachments/nav/noLicense.png",
    "typeCf008":"https://ai.hdqmjs.com/attachments/nav/noLicense.png",
    "typeCf009":"https://ai.hdqmjs.com/attachments/nav/nolanguage.png",
    "typeCf010":"https://ai.hdqmjs.com/attachments/nav/nolanguage.png",

    "navExport":"https://ai.hdqmjs.com/attachments/nav/export.png",
    "navWarning":"https://ai.hdqmjs.com/attachments/nav/warning.png",
    "navInstructions":"https://ai.hdqmjs.com/attachments/nav/instructions.png",
    "navRadio":"https://ai.hdqmjs.com/attachments/nav/radio.png",
    "navRules":"https://ai.hdqmjs.com/attachments/nav/rules.png",
    "navAdminLicence":"https://ai.hdqmjs.com/attachments/nav/adminLicence.png",
    "navDrill":"https://ai.hdqmjs.com/attachments/nav/drill.png",
    "navLicence":"https://ai.hdqmjs.com/attachments/nav/licence.png",
    "navPublicity":"https://ai.hdqmjs.com/attachments/nav/publicity.png",
    "navLifeguard":"https://ai.hdqmjs.com/attachments/nav/lifeguard.png",
    "navEmployees":"https://ai.hdqmjs.com/attachments/nav/employees.png",
    "navBook":"https://ai.hdqmjs.com/attachments/nav/book.png",
    "navTodo_white":"https://ai.hdqmjs.com/attachments/nav/todo.png",
    "navReport":"https://ai.hdqmjs.com/attachments/nav/report.png",
    "navNotice":"https://ai.hdqmjs.com/attachments/nav/notice.png",

    "navCpdx":"https://ai.hdqmjs.com/attachments/nav/cpdx.png",
    "navWcnrcp":"https://ai.hdqmjs.com/attachments/nav/wcnrcp.png",
    "navDxcf":"https://ai.hdqmjs.com/attachments/nav/dxcf.png",
    "navXy":"https://ai.hdqmjs.com/attachments/nav/xy.png",
    "navWg":"https://ai.hdqmjs.com/attachments/nav/wg.png",
    "navByz":"https://ai.hdqmjs.com/attachments/nav/byz.png",
    "navCp":"https://ai.hdqmjs.com/attachments/nav/cp.png",
    "navQfqy":"https://ai.hdqmjs.com/attachments/nav/qfqy.png",
    "navCh":"https://ai.hdqmjs.com/attachments/nav/ch.png",
    "navCf":"https://ai.hdqmjs.com/attachments/enforcement/type/cf.png",
    "navSb":"https://ai.hdqmjs.com/attachments/nav/sb.png",

    "navNosafe":"https://ai.hdqmjs.com/attachments/nav/nosafe.png",
    "navNorule":"https://ai.hdqmjs.com/attachments/nav/noRule.png",
    "navNolife":"https://ai.hdqmjs.com/attachments/nav/nolife.png",
    "navNolicense":"https://ai.hdqmjs.com/attachments/nav/noLicense.png",
    "navNolanguage":"https://ai.hdqmjs.com/attachments/nav/nolanguage.png",

    "navNoticeDark":"https://ai.hdqmjs.com/attachments/nav/notice-dark.png",
    "navData":"https://ai.hdqmjs.com/attachments/nav/data.png",
    "navZg_blue":"https://ai.hdqmjs.com/attachments/nav/zg-blue.png",
    "navCf_blue":"https://ai.hdqmjs.com/attachments/nav/cf-blue.png",
    "navEnforcement_blue":"https://ai.hdqmjs.com/attachments/nav/enforcement-blue.png",
    "navMap":"https://ai.hdqmjs.com/attachments/nav/map.png",
    "navRecord":"https://ai.hdqmjs.com/attachments/nav/record.png",
    "navRecord_white":"https://ai.hdqmjs.com/attachments/nav/record-white.png",
    "navTransform":"https://ai.hdqmjs.com/attachments/nav/transform.png",
    "navSearch":"https://ai.hdqmjs.com/attachments/nav/search.png",
    "navStreet":"https://ai.hdqmjs.com/attachments/nav/street.png",
    "navEnforcemenet":"https://ai.hdqmjs.com/attachments/nav/enforcemenet.png",
    "navEnf":"https://ai.hdqmjs.com/attachments/nav/navEnforcement.png",
    "navCompany":"https://ai.hdqmjs.com/attachments/nav/navCompany.png",
    "navStre":"https://ai.hdqmjs.com/attachments/nav/navStreet.png",
    "navEnterprise":"https://ai.hdqmjs.com/attachments/nav/enterprise.png",
    "navZg":"https://ai.hdqmjs.com/attachments/enforcement/type/zg.png",
    "navTodo":"https://ai.hdqmjs.com/attachments/nav/toDo.png",
    "navSearch_white":"https://ai.hdqmjs.com/attachments/nav/search-white.png",
    "navMap_white":"https://ai.hdqmjs.com/attachments/nav/map-white.png",
    "navEnforcement_white":"https://ai.hdqmjs.com/attachments/nav/enforcement-white.png",
    "navBook_white":"https://ai.hdqmjs.com/attachments/nav/book-white.png",
    "navReSetting_white":"https://ai.hdqmjs.com/attachments/nav/reSetting-white.png"
}







