@endpoint=https://ai.hdqmjs.com


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/500
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "我的上报", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list",
            "total":"total"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":""
          }
        }
    ], 
    "moduleData": {
        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
          "loadApi":"https://ai.hdqmjs.com/data?id=500",
          "itemNavigation": "",
          "response":{
              "list":"reportList.list",
              "total":"reportList.total"
          },
          "tabConfig":{
            "field":"type",
            "show":true
          },
          "response":{
            "list":"type.list",
            "total":"type.total"
          },
          "request":{
            "fixed":"type",
            "default":{
              "type":"0"
            },
            "pn":"pageNo",
            "ps":"pageSize"
          },
          "itemModule":{
            "type":"custom_component",
            "name":"MyReportItem"
          }
        }
    }
}


### 获取页面数据
POST {{endpoint}}/data/500 HTTP/1.1
content-type: application/json

{
    "type": {
      "list": [
          { 
						"id": "501", 
						"year": "2021年",
            "record": [
              {
                "month": "4月1日",
                "title": "这里的环境怎么那么差",
                "status": "toBeVerified",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              },
              {
                "month": "5月1日",
                "title": "这里的环境怎么那么差",
                "status": "verified",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              }
            ]
					},
          { 
						"id": "502", 
						"year": "2020年",
            "record": [
              {
                "month": "7月1日",
                "title": "这里的环境怎么那么差",
                "status": "toBeVerified",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              },
              {
                "month": "6月1日",
                "title": "这里的环境怎么那么差",
                "status": "validationFailed",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              }
            ]
					},
          { 
						"id": "503", 
						"year": "2019年",
            "record": [
              {
                "month": "7月1日",
                "title": "这里的环境怎么那么差",
                "status": "validationFailed",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              },
              {
                "month": "6月1日",
                "title": "这里的环境怎么那么差",
                "status": "verified",
                "imgList": [
                  { "id": 1, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"},
                  { "id": 2, "url": "https://img01.yzcdn.cn/vant/cat.jpeg"}
                ],
                "address": "朝阳北路102号楼7层715室(青年汇大厦)"
              }
            ]
					}
      ],
      "total": 3
    }
  }

