#### 后台管理界面
http://106.53.93.81

https://r.zbsoft.top/sport
用户名/密码：000000/000000

#### AAPI
#### 表单设计器：
https://r.zbsoft.top/form-generator

#### 移动端渲染地址：
https://r.zbsoft.top/h5-form-render

@endpoint=https://r.zbsoft.top
// 执法人员
@token=eyJleHBpcmVzX2luIjoxNjI1MDUzNTIxMjE4LCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJhY2Nlc3MiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVHlwZSI6InVzZXIiLCJ1c2VyTmFtZSI6IjAwMDAwMCIsImxvZ2luSWQiOiI0MzA3MjE3MmU0NTk0ODNkOTVlMGQ0YzM2NGI5MTdjMiIsInVzZXJJZCI6IjQzMDcyMTcyZTQ1OTQ4M2Q5NWUwZDRjMzY0YjkxN2MyIn0.Aiir-aUXBEqJWl6wT5VhpLhfh4i9BBIDBOZPc4-XRqQ
//"userId": "43072172e459483d95e0d4c364b917c2",
//"userName": "张体委",


// 执法人员 zf09
//@token=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE2LCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjE5NywiaG91ciI6MTYsIm1pbnV0ZSI6MjgsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjcwMjAwMDAwMCwic2Vjb25kIjo0MCwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiIzNzJkZDg5MjY0ZjM0YWI0YTRjYWUzMmUxMTk4NDczMSIsInJlZnJlc2hfdG9rZW4iOiJjMGE0OTlmYmY2YmM0ZDg4YjJlNGI2ZjIyNzQ1MzFiNSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjgsImRlcHRfaWQiOjMsInVzZXJuYW1lIjoiemYwOSIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI1NTYwMTIwIiwicm9sZV9jb2RlcyI6WyJBU1MiXX0.7-BpxZiUvnBmDtCK3ODnnVqN-pVd_WKWcc_bXlSTCsU


// 企业用户  qy01
@token=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE2LCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjE5NywiaG91ciI6OSwibWludXRlIjozNywibW9udGgiOiJKVUxZIiwibW9udGhWYWx1ZSI6NywibmFubyI6ODAyMDAwMDAwLCJzZWNvbmQiOjIyLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiI3NGY1MTYzNWJhYjE0NjIxOWEzNzQxMjNiYWIxYjhkMSIsInJlZnJlc2hfdG9rZW4iOiJlNTdiZTcwZGFlYjI0NDE1OTE1ZDQyZWRjMWFjMjJmMyIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjQsImRlcHRfaWQiOjE1LCJ1c2VybmFtZSI6InF5MDEiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjowLCJ0aW1lX3N0YW1wIjoiMTYyNTUzNTQ0MiIsInJvbGVfY29kZXMiOlsiUVlZSCJdfQ.vn6MSrhlHDF3B4EBqCXVL0531MWqJAZQM__wrXpO2N0

# @token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE3LCJkYXlPZldlZWsiOiJTQVRVUkRBWSIsImRheU9mWWVhciI6MTk4LCJob3VyIjoxMSwibWludXRlIjo1NiwibW9udGgiOiJKVUxZIiwibW9udGhWYWx1ZSI6NywibmFubyI6NTU1MDAwMDAwLCJzZWNvbmQiOjUxLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiI1MzZhZDE1MmRhZWY0YWJmYjZiZjZkNDNmZWRhZDZkNyIsInJlZnJlc2hfdG9rZW4iOiI2YWMzOGVhNDM3MDQ0NWI3YTIwODFkZmIyOGI5NTUwNiIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjQsImRlcHRfaWQiOjE1LCJ1c2VybmFtZSI6InF5MDEiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjowLCJ0aW1lX3N0YW1wIjoiMTYyNTYzMDIxMSIsInJvbGVfY29kZXMiOlsiUVlZSCJdfQ.pMpxs9Y4lx5Era22SAFPgVMTRgz7O8_0NbitoEW6KPg

### 删除表单
POST {{endpoint}}/api.page.design.form/deleteForm
Content-Type: application/json
accessToken: {{token}}

{
    "id": 0
}


## 表单设计接口


### 表单配置列表
#POST https://r.zbsoft.top/api.page.design.page/listPage
POST {{endpoint}}/api.page.design.page/listPage
Content-Type: application/json
accessToken: {{token}}

{
    
}

### 表单配置查询  (可以通过 code 查询)
POST {{endpoint}}/api.page.design.form/loadFormInfo
Content-Type: application/json
accessToken: {{token}}

{
    "code": "zf001"
}

# {
#     "formId": 15
# }


### 表单定义保存
POST {{endpoint}}/api.page.design.form/saveFormInfo
Content-Type: application/json
accessToken: {{token}}

{
    "id": 0,
    "jsonDefine": ""
}


### 表单数据接口
// formId：表单id，dataId数据id
POST {{endpoint}}/api.page.design.form/loadFormInfo
Content-Type: application/json
accessToken: {{token}}

{
    "code": "zf001"
}


### 表单数据分页查询
// 以下两个条件[mapWheres,listWheres]只能使用其中一个
// 查询所有表单数据
POST {{endpoint}}//api.page.design.form/listDataPage
Content-Type: application/json
accessToken: {{token}}

{
    "code": "zf001",
    "formDefine": false,
    "dataType": "group1"
}

{
    "code": "zf001",
    "formDefine": false,
    "dataId": 2,
    "listWheres": [{"O_CODE":"equal","F_CODE":"data_type","VALUE":"group1"}],
    "dataType": "group1"
}

{
    "code": "zf001",
    "dataId": 2,
    "formDefine": false
}


# {
#     "code": "zf001",
#     "mapWheres": 0,
#     "listWheres": 0
# }


### 表单数据提交
// 没有 dataId 如果为空，表示新增数据，如果不空，表示修改数据
// dataSn
POST {{endpoint}}/api.page.design.form/submitFormData
Content-Type: application/json
accessToken: {{token}}

{
    "code": "zf001",
    "version": "1",
    "dataType": "group1",
    "dataId": 11,
    "data":
    {
       "companyName": "myCompanyName2",
       "companyType": "muyCompanyType22"
    }
}


# {
#     "dataId": 0,
#     "code": "zf001",
#     "version": "1",
#     "data": 
#     {

#     }
# }


## 工作流

### 流程定义列表查询
// [zc, xzxk]

POST {{endpoint}}/api.flow.process/definitionListPage
Content-Type: application/json
accessToken: {{token}}

{
    "keyWords": ""
}


### 查询已发起的流程列表

// 出参
// applyUserId
// applyUserName
// finishState 0-未完成  1-已完成
// dataScope 1 表示当前用户
// processDefinitionKey 流程编号

// 流程发起人
 //private String actApplyUserId;
 //private String actApplyUserName;
 
// 流程状态
 //private String finishState;//完成状态。0末完成，1已完成
 
// 任务处理状态
// private String actCurrTaskName;
 //private String actCurrDualUserName;
 //private String actCurrDualUserId;
 
// 表单相关
 //private String formCode;
 //private String formName;
 //private String formVersion;
POST {{endpoint}}/api.flow.process/instanceListPage
Content-Type: application/json
accessToken: {{token}}

// 当前用户
# {
#     "dataScope": 1,
#     "processDefinitionKey": "zc",
# }

// 指定用户
{
    "processDefinitionKey": "zc",
    "actApplyUserId": "49"
}


### 表单相关v2
@endpoint1=https://api.uat.smallsaas.cn
@endpoint1=http://192.168.3.226:8000
GET {{endpoint1}}/v2/api.flow.process/instanceListPage?dataScope=1&processDefinitionKey=zc
Content-Type: application/json
accessToken: {{token}}

{
    "dataScope": 1,
    "processDefinitionKey": "zc"
}
###
POST https://api.uat.smallsaas.cn/api.flow.process/instanceListPage
Content-Type: application/json
accessToken: {{token}}

{
    "dataScope": 1,
    "processDefinitionKey": "zc"
}

### 表单相关v2
@endpoint1=http://192.168.3.226:8000
GET {{endpoint1}}/api.flow.process/instanceListPage?dataScope=1&processDefinitionKey=zc
Content-Type: application/json
accessToken: {{token}}

{
    "dataScope": 1,
    "processDefinitionKey": "zc"
}


### 流程任务列表查询 (待办)
//private String keyWords; 查询关键字,流程名称 流程id等
//private String processDefineKey;//流程定义标识
//private String queryType;//wait:我的待办,dealed:我处理过,finished:已完成
POST {{endpoint}}/api.flow.task/taskListPage
Content-Type: application/json
accessToken: {{token}}

{
     "queryType": "wait"
}

# {
#     "keyWords":"",
#     "processDefineKey":"",
#     "queryType": "wait"
# }


### 流程办理明细查询 (发起流程前获取表单编号)
// 待办事项列表需要传 taskId
//private String processDefineKey;//流程定义标识
//private String version;//版本
//private String taskId;//任务id
//private String businessKey;//业务key(表单数据 id)
POST {{endpoint}}/api.flow.examine/toComplete
Content-Type: application/json
accessToken: {{token}}

{
    "processDefineKey":"zc",
    "version":"1"
}

# {
#     "processDefineKey":"xzxk",
#     "version":"1"
# }

# {
#     "processDefineKey":"xzxk",
#     "version":"1",
#     "taskId": 0,
#     "businessKey": 0
# }


### 获取下一节点审批人
//private String processDefineKey;//流程定义标识,必填
//private String version;//流程版本
//private String taskId;//任务id，如果是开始发起流程，可不上送，如果流程审批环节，需要上送当前任务id
POST {{endpoint}}/api.flow.examine/queryNextExamineUser
Content-Type: application/json
accessToken: {{token}}

{
    "processDefineKey":"zc",
    "version":"1"
}

# {
#     "processDefineKey":"xzxk",
#     "version":"1",
#     "taskId": 0
# }


### 流程数据暂存
//private String processDefineKey;//流程定义标识
//private String version;//流程定义版本
//private String businessKey;//业务id
//private Map<String, Object> fromData;//表单数据
POST {{endpoint}}/api.flow.examine/saveTemp
Content-Type: application/json
accessToken: {{token}}

{
    "processDefineKey":"xzxk",
    "version":"1",
    "businessKey": 0,
    "fromData": 0
}

# {
#     "processDefineKey":"",
#     "version":"1",
#     "businessKey": 0,
#     "fromData": 0
# }


### 流程办理提交 (发起流程）
//private String processDefineKey;//流程定义标识
//private String version;//版本
//private String taskId;//任务id，如 果是开始发起流程，可不上送
//private String userId;//下一节点处理人
//private String userName;//下一节点处理人名字
//private String businessKey;//业务id(表单数据id)
//private Map<String, Object> fromData;//表单数据
//private String comment;//审批意见
POST {{endpoint}}/api.flow.examine/complete
Content-Type: application/json
accessToken: {{token}}

{
    "processDefineKey":"zc",
    "version":"1",
    "userId": 26,
    "userName": "张体委",
    "formData":
    {
        "field01":"9134353252",
        "field02":"企业"
    },
    "comment": "同意"
}

# {
#     "processDefineKey":"xzxk",
#     "version":"1",
#     "taskId": 0,
#     "userId": 0,
#     "userName": "",
#     "businessKey":"",
#     "fromData":{},
#     "comment": "",
#     "businessKey": 0,
#     "fromData": 0
# }


### 流程实例明细
//private String processInstanceId;//流程实例id
POST {{endpoint}}/api.flow.examine/processDetail
Content-Type: application/json
accessToken: {{token}}

{
    "processInstanceId": "80225"
}

### 1.2.3.6	审批意见列表
//审批意见列表，用于查看当前流程经过的节点及每个节点的处理意见
//private String processInstanceId;//流程实例id
POST {{endpoint}}/api.flow.examine/getComments
Content-Type: application/json
accessToken: {{token}}

{
    "processInstanceId": "40093"
}


### 1.2.3.7	获取当前节点审批人
POST {{endpoint}}/api.flow.examine/queryCurrExamineUser
Content-Type: application/json
accessToken: {{token}}

{
    "processInstanceId": "40093"
}


### 变更当前节点审批人
//String processInstanceId;//流程实例id
//private String userId;//审批人id
//private String userName;//审批人名字
POST {{endpoint}}/api.flow.examine/changeExamineUser
Content-Type: application/json
accessToken: {{token}}

{
    "processInstanceId": 0,
    "userId": "",
    "userName": ""
}


### 删除流程实例
//private String processInstanceId;//流程实例id
//private String delReason;//删除理由
//private Boolean history;//是否历史流程，如果是，则 delReason必填
POST {{endpoint}}/api.flow.examine/deleteProcessInstance
Content-Type: application/json
accessToken: {{token}}

{
    "processInstanceId": 0,
    "delReason": "",
    "history": ""
}
