## 执法小程序
  app: internal
  appid: wx225bca85b56af3aa
  AppSecret: 1ce917489d4d35aa58b155c6aadd1ec1

## 场馆小程序
  app: public
  appid: wx7bb496426db3d0ff

## 体医小程序
  app: medical
  appid: wxa618f751921754f5


### 综合桌面
https://rt.zbsoft.top
User: admin
Pw: 111111
### Swagger Doc
# https://rt.zbsoft.top/admin/swagger-ui.html

@endpoint=https://rt.zbsoft.top
@endpoint=https://api.uat.smallsaas.cn


// 企业用户  qy01
# @token=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE2LCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjE5NywiaG91ciI6OSwibWludXRlIjozNywibW9udGgiOiJKVUxZIiwibW9udGhWYWx1ZSI6NywibmFubyI6ODAyMDAwMDAwLCJzZWNvbmQiOjIyLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiI3NGY1MTYzNWJhYjE0NjIxOWEzNzQxMjNiYWIxYjhkMSIsInJlZnJlc2hfdG9rZW4iOiJlNTdiZTcwZGFlYjI0NDE1OTE1ZDQyZWRjMWFjMjJmMyIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjQsImRlcHRfaWQiOjE1LCJ1c2VybmFtZSI6InF5MDEiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjowLCJ0aW1lX3N0YW1wIjoiMTYyNTUzNTQ0MiIsInJvbGVfY29kZXMiOlsiUVlZSCJdfQ.vn6MSrhlHDF3B4EBqCXVL0531MWqJAZQM__wrXpO2N0

// 执法人员 zf09
# @token=eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE2LCJkYXlPZldlZWsiOiJGUklEQVkiLCJkYXlPZlllYXIiOjE5NywiaG91ciI6MTYsIm1pbnV0ZSI6MjgsIm1vbnRoIjoiSlVMWSIsIm1vbnRoVmFsdWUiOjcsIm5hbm8iOjcwMjAwMDAwMCwic2Vjb25kIjo0MCwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiIzNzJkZDg5MjY0ZjM0YWI0YTRjYWUzMmUxMTk4NDczMSIsInJlZnJlc2hfdG9rZW4iOiJjMGE0OTlmYmY2YmM0ZDg4YjJlNGI2ZjIyNzQ1MzFiNSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjgsImRlcHRfaWQiOjMsInVzZXJuYW1lIjoiemYwOSIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI1NTYwMTIwIiwicm9sZV9jb2RlcyI6WyJBU1MiXX0.7-BpxZiUvnBmDtCK3ODnnVqN-pVd_WKWcc_bXlSTCsU

// 执法
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjE3LCJkYXlPZldlZWsiOiJTQVRVUkRBWSIsImRheU9mWWVhciI6MTk4LCJob3VyIjoxOSwibWludXRlIjoxMCwibW9udGgiOiJKVUxZIiwibW9udGhWYWx1ZSI6NywibmFubyI6Njk2MDAwMDAwLCJzZWNvbmQiOjQsInllYXIiOjIwMjEsImNocm9ub2xvZ3kiOnsiY2FsZW5kYXJUeXBlIjoiaXNvODYwMSIsImlkIjoiSVNPIn19LCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3NfdG9rZW4iOiI5ODg5NTE4OTI4Mjk0ODM1OTQ3YzJkNmU4Yzg4N2FmYiIsInJlZnJlc2hfdG9rZW4iOiI3MDUwZGVlZDUzMmY0NjJjOTdiMmY4ZWZlNzllZGE3YiIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjIsImRlcHRfaWQiOjMsInVzZXJuYW1lIjoiemYwMSIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImxpY2VuY2UiOiJwcm9ncmVzcyIsImZyb20iOjAsInRpbWVfc3RhbXAiOiIxNjI1NjU2MjA0Iiwicm9sZV9jb2RlcyI6WyJBU1MiXX0.L_By2r_yoDFDQ-bNZze2I1qY5Uanp1xXP_t_mS1MUTU

### 用户登录
GET {{endpoint}}/user/1


### 用户授权
#### app: internal - 执法   medical - 体医  
POST {{endpoint}}/auth/oauth/token HTTP/1.1
Content-Type: application/x-form-urlencoded

{
    "auth": "0635m6ll27oPi743kDnl2ZJoMI15m6lN",
    "from": 2,
    "iv": "pXSm/gJ0HHT4AVThIUOTMw==",
    "encryptedData": "Of8fp/JwwoNQ9NWjHvgC6ebBvpZ8Bq5yN0Mu/Mse91QN1uKyjqJq3f6kcXHWM1Yr1XMAhIFR/zVYODklyXmK6QwMl8TgYvRdKmrph4yW4p7h1wGRIfi6WtqjNub1kwCkNqhvVsQCJIY42FO7KbQPlhCazC6Vebbl1JPrT5qZDTRGZhrXvJ9a5RdnL+EzelXT9VbjZEa8gt+pasPmKmChW774XcmGTY9LlLtqtSOBPXoYNHdIlFYuCQECb3H8S+Wz7kCXwNODZ7ICxTIFXbpLCD7oncPX8AsB6h3vIcVIELMJFyOxQ0Oxv0fr1pTj9HIU9lUEAreqB9+yjbSE1RaRU/tOoMPgwKtX43uDtx7gIrwzDhM+mM5lcB/wNhUPn0osOL6xstAYv2/XRpDZVHSiHuUm8sx5/TUxFFhqv8LrGlL1CyzatRl5j15E6OZOpkWTaRzUY5Qa/9T5RMwbrTNnog==",
    "app": "internal"
}


### 获取用户信息
GET {{endpoint}}/admin/user/3
Authorization: Bearer {{token}}

### 查询企业信息库
GET {{endpoint}}/admin/companyinfo/page?size=10&current=2&type=EDU
Authorization: Bearer {{token}}


### 查询企业详情
GET {{endpoint}}/admin/companyinfo/30
Authorization: Bearer {{token}}


### 查询我的企业信息
GET {{endpoint}}/admin//companyinfo/myCompany
Authorization: Bearer {{token}}
