@endpoint=https://ai.hdqmjs.com


## 动态列表
GET {{endpoint}}/form?id=77777

### 保存动态列表
POST {{endpoint}}/form/77777
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "检查记录", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":""
          }
        }
    ], 
    "dataSource":{
       "api": "https://ai.hdqmjs.com/data?id=109"
    },
    "moduleData": {
        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
          "loadApi":"https://ai.hdqmjs.com/api.flow.task/taskListPage",
          "method":"POST",
          "itemNavigation": "/workFlow/companyConfirm/companyConfirm?piId&taskId&processDefineKey&preUserName&preUserId",
          "response":{
              "list":"list"
            },
            "response":{
            "list":"list"
            },
            "request":{
            "default":{
              "queryType": "wait"
            },
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "itemModule":{
            "type":"custom_component",
            "name":"toDoListItem"
            }
        }
    }
}
