@endpoint=https://ai.hdqmjs.com

## 动态页面 

### 获取市场监督页面数据 
GET {{endpoint}}/form?id=10088


### 保存动态页面
POST {{endpoint}}/form/10088
content-type: application/json

{
    "version":"1",
    "name":"ZG",
    "title":"整改",
    "pageStyle":{},
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"autoform",
            "key":"555sd22-ad44-55ea-ca11-4225534d52b7",
            "name":"autoform",
            "container":{
                "background":"white"
            },
            "FormKey":"ZGLC",
            //"code":"zc03",
            "API":"/api.page.design.form/loadFormInfo"
        }
    ]
}

