@endpoint=https://api.mock.smallsaas.cn


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/107
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "执法", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "records":"list",
            "total":"total"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":""
          }
        }
    ], 
    "dataSource":{
       "api": "https://api.uat.smallsaas.cn/api/u/workflow/instance/list?type=CREATOR&formType=41"
    },
    "moduleData": {
        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
          "itemNavigation": "/companyHome/my/returnToWorkDetail?id",
          "response":{
              "list":"type.list",
              "total":"type.total"
          },
          "tabConfig":{
            "field":"type",
            "show":true
          },
          "response":{
            "list":"type.list",
            "total":"type.total"
          },
          "request":{
            "fixed":"type",
            "default":{
              "type":"0"
            },
            "pn":"pageNo",
            "ps":"pageSize"
          },
          "itemModule":{
            "type":"custom_component",
            "name":"SelfInspectionRecordItem"
          }
        }
    }
}

### 获取页面数据
POST {{endpoint}}/data/109 HTTP/1.1
content-type: application/json

{
    "days": 5,
    "applyList":{
        "list":[
          {
            "id": "311",
            "type": "100",
            "name": "2020年第一季度",
            "code": "2020-01-01 - 2020-03-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "START"
          },
          {
            "id": "321",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "VERIFYING"
          },
          
          {
            "id": "322",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_REJECTED"
          },
          
          {
            "id": "323",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_APPROVED"
          }
        ],
        "total": 2
    }
            
  }

