@endpoint = http://ai.hdqmjs.com
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjYsImRheU9mV2VlayI6IkZSSURBWSIsImRheU9mWWVhciI6MjE4LCJob3VyIjoxMCwibWludXRlIjoyNSwibW9udGgiOiJBVUdVU1QiLCJtb250aFZhbHVlIjo4LCJuYW5vIjoxNDAwMDAwMDAsInNlY29uZCI6OCwieWVhciI6MjAyMSwiY2hyb25vbG9neSI6eyJjYWxlbmRhclR5cGUiOiJpc284NjAxIiwiaWQiOiJJU08ifX0sInRva2VuX3R5cGUiOiJCZWFyZXIiLCJzY29wZSI6InNlcnZlciIsImFsZyI6IkhTMjU2In0.eyJhY2Nlc3NfdG9rZW4iOiI5NmE4YWE3ZGRiYTU0NjRmOTBjYTg4OTc5YmNjYmI2MSIsInJlZnJlc2hfdG9rZW4iOiI1ODhmNmQ3YmM4NzM0MzM1ODk3OWE1MTg4M2JhZDg3MiIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6MjAyLCJ1c2VybmFtZSI6ImQxYzZjMDM4ZmRhMDRjMmM4ZDEyODViYjNkMzc1NmZiIiwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwibGljZW5jZSI6InByb2dyZXNzIiwiZnJvbSI6MiwidGltZV9zdGFtcCI6IjE2MjczNTI3MDgiLCJyb2xlX2NvZGVzIjpbIlFZWUgiXSwibmlja25hbWUiOiJaSEFORyIsIm9wZW5faWQiOiJvSzBrLTR6Qm53Z003LWlfZFVsUkJPd09DdHVnIiwiYXBwIjoiaW50ZXJuYWwifQ.cfg0z7tIOsNSoKfInmrhxWBYMRrj2e9LOLCgARPOhbY

###
GET {{endpoint}}/executive/companyinfo/myCompany
Authorization: Bearer {{token}}

@tokenzf = 
###
GET {{endpoint}}/executive/companyinfo/1419492844267110401
Authorization: Bearer {{token}}
