@endpoint=https://api.mock.smallsaas.cn


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/109
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "企业", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "banner",
          "name": "",
          "key": "851344s-ad44-55ea-ca11-4225534d52b7",
          "container":{
          },
          "binding":{
            "imgList.banners" : "banners"
          }
        },
        {
          "type":"navlist",
          "name":"",
          "key":"navlist-4123-1324-5412-45ad12a445413",
          "container":{
            "background":"white",
            "padding":"10rpx 0",
            "box-shadow":"0px 0px 0px #999",
            "margin":"10rpx 0",
            "grid-template-columns":"repeat(3, 33.3333333%)"
          }
        },
        {
          "type": "cell",
          "name": "标题栏",
          "key": "e8940746-d595-11eb-bdca-0800271e55b7",
          "container":{
          },
          "binding":{
            "days":"days"
          }
        },
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":""
          }
        }
    ], 
    "dataSource":{
       "api": "https://api.mock.smallsaas.cn/data?id=109"
    },
    "moduleData": {
        "851344s-ad44-55ea-ca11-4225534d52b7":{
        },
        "navlist-4123-1324-5412-45ad12a445413":{
          "itemModule":{
              "name":"MagicItem"
          },
          "navList":[{
            "title":"我要自查",
            "svg":{
              "icon":"reSetting"
            },
            "nav":"/companyHome/selfCheck/index"
          },
          {
            "title":"我要复工",
            "svg":{
              "icon":"ReturnWork"
            },
            "nav":"/workFlow/ReturnWork"
          },
          {
            "title":"我要整改",
            "svg":{
              "icon":"selfSearch"
            },
            "nav":"/workFlow/Rectification"
          }
          ]
        },
        "e8940746-d595-11eb-bdca-0800271e55b7":{
          "param":{
            "title": "离自查上报还剩0天"
          }
        },
        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
          "loadApi":"https://api.uat.smallsaas.cn/api.flow.process/instanceListPage",
          "method":"POST",
          "itemNavigation": "/companyHome/selfExplain?piId",
          "response":{
              "list":"list"
          },
          "response":{
            "list":"list"
          },
          "request":{
            "default":{
              "dataScope": 1,
              "processDefinitionKey": "zc"
            },
              "pn":"pageNo",
              "ps":"pageSize"
          },
          "itemModule":{
            "type":"custom_component",
            "name":"stateToItem"
          }
        }
    }
}

### 获取页面数据
POST {{endpoint}}/data/109 HTTP/1.1
content-type: application/json

{
    "days": 5,
    "applyList":{
        "list":[
          {
            "id": "311",
            "type": "100",
            "name": "2020年第一季度",
            "code": "2020-01-01 - 2020-03-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "START"
          },
          {
            "id": "321",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "VERIFYING"
          },
          
          {
            "id": "322",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_REJECTED"
          },
          
          {
            "id": "323",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_APPROVED"
          }
        ],
        "total": 2
    },
    "imgList":{
        "banners": [
            {
                "img": "http://culturetv.hanyastar.com.cn/standard/pic/340/888/1418/30910_2015-05-09.jpg",
                "itemNavigation": "/?id=1"
            },
            {
                "img": "http://culturetv.hanyastar.com.cn/standard/pic/335/369/3854/54844_2017-02-28.jpg",
                "itemNavigation": "/?id=1"
            }
        ]
    }
            
  }

