@endpoint=https://ai.hdqmjs.com


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/109
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "企业", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "banner",
          "name": "",
          "key": "851344s-ad44-55ea-ca11-4225534d52b7",
          "container":{
          },
          "binding":{
            "imgList.banners" : "banners"
          }
        },
        {
          "type":"navlist",
          "name":"",
          "key":"navlist-4123-1324-5412-45ad12a445413",
          "container":{
            "background":"white",
            "padding":"10rpx 0",
            "box-shadow":"0px 0px 0px #999",
            "margin":"10rpx 0",
            "grid-template-columns":"repeat(4, 25%)"
          }
        },

        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":"",
            "background":"white"
          }
        }
    ], 
    "dataSource":{
       "api": "https://ai.hdqmjs.com/data?id=109"
    },
    "moduleData": {
        "851344s-ad44-55ea-ca11-4225534d52b7":{
        },
        "navlist-4123-1324-5412-45ad12a445413":{
          "itemModule":{
              "name":"MagicItem"
          },
          "navList":[{
            "title":"自查上报",
            "svg":{
              "icon":"reSetting"
            },
            "nav":"/companyHome/selfCheck/index"
          },
          {
            "title":"经营状况上报",
            "svg":{
              "icon":"returnWork"
            },
            "nav":"/workFlow/ReturnWork"
          },
          {
             "title":"执业人员登记",
            "svg":{
              "icon":"aqyReport"
            },
            "nav":"/defaultPage/defaultPage?id=53125"
          },
          {
            "title":"检查记录",
            "svg":{
              "icon":"selfSearch"
            },
            "nav":"/defaultPage/defaultPage?id=77777"
          }
          ]
        },

        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
          "loadApi":"https://ai.hdqmjs.com/api.flow.task/taskListPage",
          "method":"POST",
          "itemNavigation": "/workFlow/companyConfirm/companyConfirm?piId&taskId&processDefineKey&preUserName&preUserId",
          "response":{
              "list":"list"
            },
            "response":{
            "list":"list"
            },
            "request":{
            "default":{
              "queryType": "wait"
            },
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "itemModule":{
            "type":"custom_component",
            "name":"toDoListItem"
            }
        }
    }
}

### 获取页面数据
POST {{endpoint}}/data/109 HTTP/1.1
content-type: application/json

{
    "days": 5,
    "applyList":{
        "list":[
          {
            "id": "311",
            "type": "100",
            "name": "2020年第一季度",
            "code": "2020-01-01 - 2020-03-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "START"
          },
          {
            "id": "321",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "VERIFYING"
          },
          
          {
            "id": "322",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_REJECTED"
          },
          
          {
            "id": "323",
            "type": "200",
            "name": "2020年第二季度",
            "code": "2020-01-01 - 2020-05-31",
            "createTime": "2020-3-25 12:12:12",
            "status": "CLOSE_APPROVED"
          }
        ],
        "total": 2
    },
    "imgList":{
        "banners": [
            {
                "img": "https://ai.hdqmjs.com/attachments/banner/banner.png",
                "itemNavigation": "/?id=1"
            }
        ]
    }
            
  }

