@endpoint = https://api.mock.smallsaas.cn

## 动态列表主页
# 跳转路由
# 前往各个子项
# 本页只提供路由跳转功能
### 获取列表主页数据
GET {{endpoint}}/form?id=1025
content-type: application/json


### 保存列表主页数据
POST {{endpoint}}/form/1025
content-type: application/json

{
    "version":"1",
    "name":"auto_list_page",
    "title":"页面组件展示",
    "pageStyle":{},
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"navlist",
            "key":"1172222-ad44-55ea-ca11-4225534d52b7",
            "name":"cardListItem",
            "container":{
            "grid-template-columns":"repeat(3, 33.33333333%)"
            }
        },
        {
            "type":"navlist",
            "key":"1175555-ad44-55ea-ca11-4225534d52b7",
            "name":"MagicItem",
            "container":{
            "grid-template-columns":"repeat(2, 50%)"
            } 
        },
        {
            "type":"navlist",
            "name":"subTitleCardItem",
            "key":"d4a555sd-hf22-qqds-8412-16234da445885",
            "container":{
                "grid-template-columns":"repeat(2, 50%)"
            }
        }
    ],
    "moduleData":{
        "1172222-ad44-55ea-ca11-4225534d52b7":{
            "itemModule":{
              "name":"cardListItem"
           },
             "navList": [
              {
                "svg":"record",
                "title":"record",
                "nav":"/",
                "container":{
                }
              },
            {
                "svg":"map",
                "title":"map",
                "nav":"/",
                "container":{
                }
              },
            {
                "svg":"search",
                "title":"search",
                "nav":"/",
                "container":{
                }
              },
              {
                  "svg":"data",
                  "title":"data",
                  "nav":"/",
                  "container":{
                  }
              },
              {
                  "svg":"transform",
                  "title":"transform",
                  "nav":"/",
                  "container":{
                  }
              },
              {
                  "svg":"book",
                  "title":"book",
                  "nav":"/",
                  "container":{
                  }
              },
              {
                  "img":"https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimages.669pic.com%2Felement_pic%2F43%2F57%2F83%2F1%2F3ed3001c3e5cdcc467b8d4f0dfe7d8df.jpg%21w700wb&refer=http%3A%2F%2Fimages.669pic.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1626925236&t=7a61c0d83d362d16e68fc8a5ac3eb313",
                  "title":"图片",
                  "nav":"/",
                  "container":{
                  }
              },
                {
                  "title":"background",
                  "nav":"/",
                  "container":{
                      "background":"#45D7AA"
                  }
              }
            ]
        },
        "1175555-ad44-55ea-ca11-4225534d52b7":{
            "itemModule":{
                "name":"MagicItem"
            },
            "navList":[
                {
                    "title":"export",
                    "svg":{
                        "icon":"export",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"warning",
                    "svg":{
                        "icon":"warning",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"instructions",
                    "svg":{
                        "icon":"instructions",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"radio",
                    "svg":{
                        "icon":"radio",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"rules",
                    "svg":{
                        "icon":"rules",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"adminLicence",
                    "svg":{
                        "icon":"adminLicence",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"drill",
                    "svg":{
                        "icon":"drill",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"licence",
                    "svg":{
                        "icon":"licence",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"publicity",
                    "svg":{
                        "icon":"publicity",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"lifeguard",
                    "svg":{
                        "icon":"lifeguard",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"employees",
                    "svg":{
                        "icon":"employees",
                        "color":"#888"
                    },
                    "nav":"/"
                },
                {
                    "title":"图片",
                    "img":"https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=32822217,3902783693&fm=26&gp=0.jpg",
                    "nav":"/"
                },
                {
                    "title":"container样式",
                    "svg":{
                        "icon":"employees"
                    },
                    "nav":"/",
                    "container":{
                        "color":"white",
                        "background":"#45D7AA"
                    }
                }
            ]
        },
                "d4a555sd-hf22-qqds-8412-16234da445885": {
            "itemModule":{
              "name":"subTitleCardItem"
           },
            "navList": [
              {
                "svg":"enforcement",
                "title":"enforcement",
                "subTitle":"enforcement副标题",
                "nav":"/",
                "container":{
                }
              },
              {
                "svg":"enterprise",
                "title":"enterprise",
                "subTitle":"enterprise副标题",
                "nav":"/",
                "container":{
                }
              },
              {
                "svg":"street",
                "title":"street",
                "subTitle":"street副标题",
                "nav":"/",
                "container":{
                }
              },
              {
                "svg":"management",
                "title":"management",
                "subTitle":"management副标题",
                "nav":"/",
                "container":{
                }
              },
              {
                "img":"https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=32822217,3902783693&fm=26&gp=0.jpg",
                "title":"图片",
                "subTitle":"图片副标题",
                "nav":"/",
                "container":{
                }
              },
              {
                "svg":"management",
                "title":"container样式",
                "subTitle":"container样式副标题",
                "nav":"/",
                "container":{
                    "background":"#45D7AA"
                }
              }
            ]
        }
    }
}