@endpoint = https://ai.hdqmjs.com

### 获取除表单外的页面数据
GET {{endpoint}}/form?id=66000


### 设置除表单外的页面数据
POST {{endpoint}}/form/66000 HTTP/1.1
Content-Type: application/json

{  
    "version": "1",
    "name": "Approval comments",
    "title": "办理意见",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type":"confirm",
        "name":"",
        "key":"89084045-v4d5-7122-3300-1623511112885"
      },
      {
        "type":"getWorkFlow",
        "name":"",
        "key":"84653120-4521-5120-1302-5132231846513"
      }
    ],
    "moduleData": {
        "89084045-v4d5-7122-3300-1623511112885": {
            "agreeText":"提交",
            "lastText":"回退",
            "refuseText":"不合格",
            "placeholder":"办理意见",
            "groupText":"办理记录",
            "failUrl":"/cofirmRefuse/cofirmRefuse",
            "query":{
                "key":"zglc"
            },
            "noCommit":true,
            "hideConfirm":true
        },
        "84653120-4521-5120-1302-5132231846513":{
          "workflow":[
            {
              "title":"整改",
              "url":"/defaultPage/defaultPage",
              "icon":"zg",
              "query":{
                "id":"3333336"
              }
            },
            {
              "title":"处罚",
              "url":"/defaultPage/defaultPage",
              "icon":"cf",
              "query":{
                "id":"3333337"
              }
            }
          ]
        }
    }
}



### 企业审批

@endpoint = https://ai.hdqmjs.com

### 获取除表单外的页面数据
GET {{endpoint}}/form?id=66001


### 设置除表单外的页面数据
POST {{endpoint}}/form/66001 HTTP/1.1
Content-Type: application/json

{  
    "version": "1",
    "name": "Approval comments",
    "title": "办理意见",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type":"confirm",
        "name":"",
        "key":"89084045-v4d5-7122-3300-1623511112885"
      }
    ],
    "moduleData": {
        "89084045-v4d5-7122-3300-1623511112885": {
            "agreeText":"提交",
            "lastText":"回退",
            "refuseText":"不合格",
            "placeholder":"办理意见",
            "hideConfirm":true,
            "noCommit":true,
            "query":{
                "key":"zglc"
            }
        }
    }
}
