@endpoint = https://api.mock.smallsaas.cn

## 动态列表主页
# 跳转路由
# 前往各个子项
# 本页只提供路由跳转功能
### 获取列表主页数据
GET {{endpoint}}/form?id=2015
content-type: application/json


### 保存列表主页数据
POST {{endpoint}}/form/2015
content-type: application/json

{
    "version":"1",
    "name":"enforcementRecordDetails",
    "title":"企业执法记录详情",
    "pageStyle":{
        "background":"#EFEFEF",
        "margin":"0",
        "padding":"0"
    },
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
        "background":"#EFEFEF"
    },
    "modules":[
        {
            "type":"autoform",
            "key":"autoform-1654-dads-54as-456a4sd1a23s",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        },
        {
            "type":"autoform",
            "key":"autoform-1561-4510-da51-46511231554",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        },
        {
            "type":"autoform",
            "key":"autoform-4564-1210-2151-445121231554",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        },
        {
            "type":"autoform",
            "key":"autoform-1243-4321-ad52-ad121x5d0242",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        },
        {
          "type": "autolist",
          "name": "审批记录",
          "binding":
          {
            "list":"list",
            "total":"total"
          },
          "bindingTarget": "data",
          "key":"autolist-7865-11ca-ds94-1420271e55b7",
          "container":{
            "height":"285px"
          }
        },
        {
            "type":"autoform",
            "key":"autoform-7654-5564-adsa-adasasaf1512",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        },
        {
            "type":"autoform",
            "key":"autoform-7512-5564-adsa-adasasaf1512",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px",
                "margin":"10px"
            }
        }
    ],
    "moduleData":{
        "autoform-1654-dads-54as-456a4sd1a23s":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields":[
                {
                    "__config__":{
                        "label":"执法单号",
                        "labelWidth":null,
                        "showLabel":true,
                        "tag":"el-input",
                        "tagIcon":"input",
                        "required":false,
                        "defaultValue":"",
                        "layout":"colFormItem",
                        "regList":[],
                        "formId":110,
                        "renderKey":1621415432107
                    },
                    "__slot__":{
                        "prepend":"",
                        "append":""
                    },
                    "placeholder":"执法单号",
                    "style":{
                        "width":"100%"
                    },
                    "clearable":true,
                    "prefix-icon":"",
                    "suffix-icon":"",
                    "maxlength":null,
                    "show-word-limit":false,
                    "readonly":true,
                    "disabled":false,
                    "__vModel__":"enforcementId"
                },
                {
                    "__config__":{
                        "label":"执法时间",
                        "labelWidth":null,
                        "showLabel":true,
                        "tag":"el-input",
                        "tagIcon":"input",
                        "required":false,
                        "defaultValue":"",
                        "layout":"colFormItem",
                        "regList":[],
                        "formId":110,
                        "renderKey":1621415432107
                    },
                    "__slot__":{
                        "prepend":"",
                        "append":""
                    },
                    "placeholder":"执法时间",
                    "style":{
                        "width":"100%"
                    },
                    "clearable":true,
                    "prefix-icon":"",
                    "suffix-icon":"",
                    "maxlength":null,
                    "show-word-limit":false,
                    "readonly":true,
                    "disabled":false,
                    "__vModel__":"enforcementTime"
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
         },
        "autoform-1561-4510-da51-46511231554":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"企业信息",
                        "children":[
                            {
                                "__config__":{
                                    "label":"名称",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"名称",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"name"
                            },
                            {
                                "__config__":{
                                    "label":"法定代表人",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"法定代表人",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"people"
                            },
                            {
                                "__config__":{
                                    "label":"场所地址",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"场所地址",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"address"
                            },
                            {
                                "__config__":{
                                    "label":"成立日期",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"成立日期",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"date"
                            },
                            {
                                "__config__":{
                                    "label":"联系电话",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"联系电话",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"phone"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "autoform-4564-1210-2151-445121231554":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"执法人信息",
                        "children":[
                            {
                                "__config__":{
                                    "label":"执法人员姓名",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"执法人员姓名",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"officerName"
                            },
                            {
                                "__config__":{
                                    "label":"证号",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"证号",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"cardNumber"
                            },
                            {
                                "__config__":{
                                    "label":"记录人",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"记录人",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"noteTaker"
                            },
                            {
                                "__config__":{
                                    "label":"被检查人",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"被检查人",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"examinee"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "autoform-1243-4321-ad52-ad121x5d0242":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"执法信息",
                        "children":[
                            {
                                "__config__":{
                                    "label":"检查事项",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查事项",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionItems"
                            },
                            {
                                "__config__":{
                                    "label":"检查子事项",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查子事项",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionSubItems"
                            },
                            {
                                "__config__":{
                                    "label":"检查内容",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查内容",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionContent"
                            },
                            {
                                "__config__":{
                                    "label":"检查方法",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查方法",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionMethod"
                            },
                            {
                                "__config__":{
                                    "label":"检查结果",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查结果",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionResults"
                            },
                            {
                                "__config__":{
                                    "label":"检查结论",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"检查结论",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"InspectionConclusion"
                            },
                            {
                                "__config__":{
                                "layout":"rowFormItem",
                                "tagIcon":"row",
                                "layoutTree":true,
                                "formId":112,
                                "renderKey":1621415404383,
                                "componentName":"图片和视频",
                                "children":[
                                    {
                                        "__config__":{
                                            "label":"图片",
                                            "labelWidth":null,
                                            "showLabel":true,
                                            "tag":"c-image",
                                            "tagIcon":"c-image",
                                            "required":false,
                                            "defaultValue":"",
                                            "layout":"colFormItem",
                                            "regList":[],
                                            "formId":110,
                                            "renderKey":1621415432107
                                        },
                                        "__slot__":{
                                            "prepend":"",
                                            "append":""
                                        },
                                        "placeholder":"",
                                        "style":{
                                            "width":"100%"
                                        },
                                        "clearable":true,
                                        "prefix-icon":"",
                                        "suffix-icon":"",
                                        "maxlength":null,
                                        "show-word-limit":false,
                                        "readonly":true,
                                        "disabled":false,
                                        "__vModel__":"images"
                                    },
                                    {
                                        "__config__":{
                                            "label":"视频",
                                            "labelWidth":null,
                                            "showLabel":true,
                                            "tag":"c-video",
                                            "tagIcon":"c-video",
                                            "required":false,
                                            "defaultValue":"",
                                            "layout":"colFormItem",
                                            "regList":[],
                                            "formId":110,
                                            "renderKey":1621415432107
                                        },
                                        "__slot__":{
                                            "prepend":"",
                                            "append":""
                                        },
                                        "placeholder":"",
                                        "style":{
                                            "width":"100%"
                                        },
                                        "clearable":true,
                                        "prefix-icon":"",
                                        "suffix-icon":"",
                                        "maxlength":null,
                                        "show-word-limit":false,
                                        "readonly":true,
                                        "disabled":false,
                                        "__vModel__":"videos"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "autolist-7865-11ca-ds94-1420271e55b7":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "response":{
                "list":"records.list",
                "total":"records.total"
            },
            "tabConfig":{
                "field":"records",
                "show":true
            },
            "response":{
                "list":"records.list",
                "total":"records.total"
            },
            "request":{
                "fixed":"type",
                "default":{
                "type":"0"
                },
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "itemModule":{
                "type":"custom_component",
                "name":"RecordStepsItem"
            }
        },
        "autoform-7654-5564-adsa-adasasaf1512":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"整改详情",
                        "children":[
                            {
                                "__config__":{
                                    "label":"整改时间",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改时间",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationTime1"
                            },
                            {
                                "__config__":{
                                    "label":"整改次数",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改次数",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationCount1"
                            },
                            {
                                "__config__":{
                                    "label":"整改地址",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改地址",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationAddress1"
                            },
                            {
                                "__config__":{
                                    "label":"整改内容",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改内容",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationContent1"
                            },
                            {
                                "__config__":{
                                    "label":"整改措施",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改措施",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationMeasures1"
                            },
                            {
                                "__config__":{
                                    "label":"图片",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"c-image",
                                    "tagIcon":"c-image",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"Rectificationimages1"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        },
        "autoform-7512-5564-adsa-adasasaf1512":{
            "loadApi":"https://api.mock.smallsaas.cn/data?id=2015",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"整改详情",
                        "children":[
                            {
                                "__config__":{
                                    "label":"整改时间",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改时间",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationTime2"
                            },
                            {
                                "__config__":{
                                    "label":"整改次数",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改次数",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationCount2"
                            },
                            {
                                "__config__":{
                                    "label":"整改地址",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改地址",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationAddress2"
                            },
                            {
                                "__config__":{
                                    "label":"整改内容",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改内容",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationContent2"
                            },
                            {
                                "__config__":{
                                    "label":"整改措施",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"整改措施",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"RectificationMeasures2"
                            },
                            {
                                "__config__":{
                                    "label":"图片",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"c-image",
                                    "tagIcon":"c-image",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"Rectificationimages2"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        }
    }
}
        

### 获取表单数据
GET {{endpoint}}/data?id=2015 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存表单数据
POST {{endpoint}}/data/2015 HTTP/1.1
content-type: application/json

{
    "enforcementId":"23847563928174",
    "enforcementTime":"2021-03-14 12:03:56",
    "name":"北京天翔文化产业有限公司",
    "people":"王伟伟",
    "address":"北京市海淀区文化产业园A8901",
    "date":"2020年3月1日",
    "phone":"13666000111",
    "officerName":"张三",
    "cardNumber":"111111111111111111",
    "noteTaker":"李四",
    "examinee":"王五",
    "InspectionItems":"对经营高危险性体育项目的行政许可",
    "InspectionSubItems":"对经营高危险性体育项目的行政许可",
    "InspectionContent":"对申报高危险性体育项目许可经营单位体育设施符合相关国家标准的说明性材料内容进行现场核查",
    "InspectionMethod":"实地勘察",
    "InspectionResults":"不符合",
    "InspectionConclusion":"不合格",
    "images":[
        {"url":"","title":""},
        {"url":"","title":""}
    ],
    "videos":[
        {"url":"https://vd4.bdstatic.com/mda-kikup5ivsj9rt0iu/hd/mda-kikup5ivsj9rt0iu.mp4?v_from_s=hkapp-haokan-hna&auth_key=1624879595-0-0-4d63965e5cef91dbeae0237fa2ad9c4c&bcevod_channel=searchbox_feed&pd=1&pt=3&abtest=","title":""},
        {"url":"https://vd4.bdstatic.com/mda-kikup5ivsj9rt0iu/hd/mda-kikup5ivsj9rt0iu.mp4?v_from_s=hkapp-haokan-hna&auth_key=1624879595-0-0-4d63965e5cef91dbeae0237fa2ad9c4c&bcevod_channel=searchbox_feed&pd=1&pt=3&abtest=","title":""}
    ],
    "records":{
        "list": [
        {
            "recordSteps": [
                    {
                        "text": "2020-12-20 12:12:12",
                        "descLabel": "审批状态: ",
                        "desc": "通过",
                        "inactiveIcon": "circle",
                        "isLink": false
                    },
                    {
                        "text": "2020-12-20 12:12:12",
                        "descLabel": "审批状态: ",
                        "desc": "通过",
                        "opinionLabel": "审批意见: ",
                        "opinion": "环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁环境不够整洁",
                        "inactiveIcon": "circle",
                        "isLink": false
                    }
                ]
            }
        ]
    },
    "RectificationTime1":"2020-12-13 12:12:12",
    "RectificationCount1":"1次",
    "RectificationAddress1":"北京市海淀区文化产业园A8901",
    "RectificationContent1":"安全出口处道路堵塞，封闭",
    "RectificationMeasures1":"将安全出口处重新修建",
    "Rectificationimages1":[
        {"url":"","title":""},
        {"url":"","title":""},
        {"url":"","title":""}
    ],
    "RectificationTime2":"2020-12-22 12:12:12",
    "RectificationCount2":"2次",
    "RectificationAddress2":"北京市海淀区文化产业园A8901",
    "RectificationContent2":"安全出口处道路堵塞，封闭",
    "RectificationMeasures2":"将安全出口处重新修建",
    "Rectificationimages2":[
        {"url":"","title":""},
        {"url":"","title":""},
        {"url":"","title":""}
    ]
}