@endpoint = https://ai.hdqmjs.com

## 动态列表主页
# 跳转路由
# 前往各个子项
# 本页只提供路由跳转功能
### 获取列表主页数据
GET {{endpoint}}/form?id=2012
content-type: application/json


### 保存列表主页数据
POST {{endpoint}}/form/2012
content-type: application/json

{
    "version":"1",
    "name":"enforcementDetails",
    "title":"企业自查详情",
    "pageStyle":{
        "margin-top":"0px",
        "padding-top":"50px",
        "background":"#1A5EB5"
    },
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"autoform",
            "key":"autoform-1561-4510-da51-46511231554",
            "name":"",
            "container":{
                "background":"white",
                "border-radius":"10px 10px 0 0"
            }
        }
    ],
    "moduleData":{
        "autoform-1561-4510-da51-46511231554":{
            "loadApi":"https://ai.hdqmjs.com/data?id=2012",
            "fields": [
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"企业信息",
                        "children":[
                            {
                                "__config__":{
                                    "label":"名称",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"名称",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"name"
                            },
                            {
                                "__config__":{
                                    "label":"法定代表人",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"法定代表人",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"people"
                            },
                            {
                                "__config__":{
                                    "label":"场所地址",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"textarea",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"场所地址",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"address"
                            },
                            {
                                "__config__":{
                                    "label":"成立日期",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"成立日期",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"date"
                            },
                            {
                                "__config__":{
                                    "label":"企业负责人联系电话",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"企业负责人联系电话",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"phone"
                            }
                        ]
                    }
                },
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"证件",
                        "children":[
                            {
                                "__config__":{
                                    "label":"营业执照",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"c-image",
                                    "tagIcon":"c-image",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"",
                                "style":{
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"certificates"
                            }
                        ]
                    }
                },
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404383,
                        "componentName":"现场照片",
                        "children":[
                            {
                                "__config__":{
                                    "label":"",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"c-image",
                                    "tagIcon":"c-image",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"",
                                "style":{
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"scenePhoto"
                            }
                        ]
                    }
                },
                {
                    "__config__":{
                        "layout":"rowFormItem",
                        "tagIcon":"row",
                        "layoutTree":true,
                        "formId":112,
                        "renderKey":1621415404384,
                        "componentName":"自查事项",
                        "children":[
                            {
                                "__config__":{
                                    "label":"自查项#1",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"自查项#1",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"select1"
                            },
                            {
                                "__config__":{
                                    "label":"自查项#2",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"自查项#2",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"select2"
                            },
                            {
                                "__config__":{
                                    "label":"自查项#3",
                                    "labelWidth":null,
                                    "showLabel":true,
                                    "tag":"el-input",
                                    "tagIcon":"input",
                                    "required":false,
                                    "defaultValue":"",
                                    "layout":"colFormItem",
                                    "regList":[],
                                    "formId":110,
                                    "renderKey":1621415432107
                                },
                                "__slot__":{
                                    "prepend":"",
                                    "append":""
                                },
                                "placeholder":"自查项#3",
                                "style":{
                                    "width":"100%"
                                },
                                "clearable":true,
                                "prefix-icon":"",
                                "suffix-icon":"",
                                "maxlength":null,
                                "show-word-limit":false,
                                "readonly":true,
                                "disabled":false,
                                "__vModel__":"select3"
                            }
                        ]
                    }
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false
        }
    }
}
        

### 获取表单数据
GET {{endpoint}}/data?id=2012 HTTP/1.1
content-type: application/json
User-Agent: rest-client

### 保存表单数据
POST {{endpoint}}/data/2012 HTTP/1.1
content-type: application/json

{
    "name":"北京天翔文化产业有限公司",
    "people":"王伟伟",
    "address":"北京市海淀区文化产业园A8901",
    "date":"2020年3月1日",
    "phone":"13666000111",
    "certificates":[
        {"url":"","title":"营业执照"},
        {"url":"","title":"许可"}
    ],
    "scenePhoto":[
        {"url":"","title":""},
        {"url":"","title":""},
        {"url":"","title":""}
    ],
    "select1":"选项内容",
    "select2":"选项#1",
    "select3":"技术咨询"
}