@endpoint=https://api.mock.smallsaas.cn

###
GET {{endpoint}}/form?id=3000
###
POST {{endpoint}}/form/3000
content-type: application/json

{
     "version":"1",
    "name":"SelfFirst",
    "title":"企业入库",
    "pageStyle":{
    },
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"steps",
            "key":"steps-6161-5a11-641c-4a63dsa540a12",
            "name":"",
            "container":{
                "background":"#1A5EB5"
            }
        },
        {
            "type":"autoform",
            "key":"autoform-13ad-a454-318a-4ad84254sd12",
            "name":"营业执照",
            "container":{
                "background":"white"
            }
        }
    ],
    "moduleData":{
        "steps-6161-5a11-641c-4a63dsa540a12":{
            "steps":{
                "step":[
                    {
                        "text": "营业执照"
                    },
                    {
                        "text": "联系人信息"
                    },
                    {
                        "text": "档案信息"
                    }
                ],
                "active":1
            }
        },
        "autoform-13ad-a454-318a-4ad84254sd12":{
  "fields": [{
    "__config__": {
      "layout": "rowFormItem",
      "tagIcon": "row",
      "layoutTree": true,
      "document": "https://element.eleme.cn/#/zh-CN/component/layout#row-attributes",
      "span": 24,
      "formId": 118,
      "renderKey": "1181625632418195",
      "componentName": "营业执照",
      "children": [{
        "__config__": {
          "label": "名称",
          "labelWidth": null,
          "showLabel": true,
          "changeTag": true,
          "tag": "el-input",
          "tagIcon": "input",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "regList": [],
          "formId": 102,
          "renderKey": "1021625631763135"
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "企业名称",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "name"
      }, {
        "__config__": {
          "label": "法定代表人",
          "labelWidth": null,
          "showLabel": true,
          "changeTag": true,
          "tag": "el-input",
          "tagIcon": "input",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "regList": [],
          "formId": 103,
          "renderKey": "1031625631820433"
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "法定代表人姓名",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "legalPerson"
      }, {
        "__config__": {
          "label": "住所",
          "labelWidth": null,
          "showLabel": true,
          "changeTag": true,
          "tag": "el-input",
          "tagIcon": "input",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "regList": [],
          "formId": 104,
          "renderKey": "1041625631866977"
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "法定代表人住所",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "address"
      }, {
        "__config__": {
          "label": "类型",
          "labelWidth": null,
          "showLabel": true,
          "changeTag": true,
          "tag": "el-input",
          "tagIcon": "input",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "regList": [],
          "formId": 108,
          "renderKey": "1081625631937680"
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "企业类型",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "type"
      }, {
        "__config__": {
          "label": "注册资本",
          "labelWidth": null,
          "showLabel": true,
          "changeTag": true,
          "tag": "el-input",
          "tagIcon": "input",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "regList": [],
          "formId": 109,
          "renderKey": "1091625632011377"
        },
        "__slot__": {
          "prepend": "",
          "append": ""
        },
        "placeholder": "企业注册资本",
        "style": {
          "width": "100%"
        },
        "clearable": true,
        "prefix-icon": "",
        "suffix-icon": "",
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "RegisteredCapital"
      }, {
        "__config__": {
          "label": "成立日期",
          "tag": "el-date-picker",
          "tagIcon": "date",
          "defaultValue": null,
          "showLabel": true,
          "labelWidth": null,
          "span": 24,
          "layout": "colFormItem",
          "required": false,
          "regList": [],
          "changeTag": true,
          "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
          "formId": 112,
          "renderKey": "1121625632097909"
        },
        "placeholder": "企业成立日期",
        "type": "date",
        "style": {
          "width": "100%"
        },
        "disabled": false,
        "clearable": true,
        "format": "yyyy-MM-dd",
        "value-format": "yyyy-MM-dd",
        "readonly": false,
        "__vModel__": "DateOfIncorporation"
      }, {
        "__config__": {
          "label": "营业期限",
          "tag": "el-date-picker",
          "tagIcon": "date",
          "defaultValue": null,
          "showLabel": true,
          "labelWidth": null,
          "span": 24,
          "layout": "colFormItem",
          "required": false,
          "regList": [],
          "changeTag": true,
          "document": "https://element.eleme.cn/#/zh-CN/component/date-picker",
          "formId": 120,
          "renderKey": "1201625632672090"
        },
        "placeholder": "请选择营业期限",
        "type": "date",
        "style": {
          "width": "100%"
        },
        "disabled": false,
        "clearable": true,
        "format": "yyyy-MM-dd",
        "value-format": "yyyy-MM-dd",
        "readonly": false,
        "__vModel__": "BusinessTerm"
      }, {
        "__config__": {
          "label": "企业经营范围",
          "labelWidth": null,
          "showLabel": true,
          "tag": "el-input",
          "tagIcon": "textarea",
          "required": false,
          "layout": "colFormItem",
          "span": 24,
          "regList": [],
          "changeTag": true,
          "document": "https://element.eleme.cn/#/zh-CN/component/input",
          "formId": 116,
          "renderKey": "1161625632314236"
        },
        "type": "textarea",
        "placeholder": "请输入企业经营范围",
        "autosize": {
          "minRows": 4,
          "maxRows": 4
        },
        "style": {
          "width": "100%"
        },
        "maxlength": null,
        "show-word-limit": false,
        "readonly": false,
        "hidden": false,
        "disabled": false,
        "__vModel__": "BusinessScope"
      }]
    },
    "type": "default",
    "justify": "start",
    "align": "top"
  }],
  "formRef": "elForm",
  "formModel": "formData",
  "size": "medium",
  "labelPosition": "right",
  "labelWidth": 100,
  "formRules": "rules",
  "gutter": 15,
  "disabled": false,
  "span": 24,
  "formBtns": false,
  "nextBtns":true,
  "NextNavigation":"/addCompany/contactInformation",
  "saveApi": "",
  "loadApi": "",
  "isLawForm": false
}

    }
}