@endpoint=http://hode1.host.smallsaas.cn:10000

### 获取视频关键帧
POST {{endpoint}}/api/ai/coach/keypose_frame
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json; charset=utf-8

{
    "video_url" : "./video1.mp4",
    "frame_position" : "00:00:02"
}
