@endpoint=https://ai.hdqmjs.com

## 动态页面 

### 获取市场监督页面数据 
GET {{endpoint}}/form?id=79422


### 保存动态页面数据
POST {{endpoint}}/form/79422
content-type: application/json

{  
    "version": "1",
    "name": "ZGJL",
    "title": "整改记录",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type":"autolist",
        "name":"",
        "key":"46412315-8775-1545-5646-8711645452154"
      }
    ],
    "moduleData": {
         "46412315-8775-1545-5646-8711645452154": {
            "loadApi":"https://ai.hdqmjs.com/api.flow.process/instanceListPage",
          "method":"POST",
            "itemNavigation": "/companyHome/selfExplain?piId",
            "response":{
                "list":"list"
            },
            "request":{
                "default":{
                  "formType":"zg"
                },
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "itemModule":{
                "type":"custom_component",
                "name":"company-state-to-enforcement"
            },
            "options":{
              "hideState":true,
              "hideNext":true,
              "timeText":"企业名称",
              "timeField":"customValues.companyName",
              "userText":"街道名称",
              "userField":"customValues.streetName"
            }
         }
    }
}