@endpoint=https://ai.hdqmjs.com


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/120
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "复工记录", 
    "pageStyle": { }, 
    "loadApi": "https://ai.hdqmjs.com/data?id=200", 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list",
            "total":"total"
          },
          "bindingTarget": "data",
          "key":"a1417b8a-d351-11eb-bb26-0800271e55b7",
          "container":{
            "height":""
          }
        }
    ], 
    "moduleData": {
        "a1417b8a-d351-11eb-bb26-0800271e55b7": {
            "loadApi":"https://ai.hdqmjs.com/api.flow.process/instanceListPage",
            "method":"POST",
            //"itemNavigation": "/enforcement/book/moreBook?piId",
            "itemNavigation": "/enforcement/book/moreBook?piId",
            "response":{
                "list":"list"
            },
            "request":{
                "default":{
                  "processDefinitionKey": "fg"
                  //"finishState":0,
                  //"formType":"zf",
                  //"customValues":{
                  //  "fileseq":"0"
                  //}
                },
                "pn":"pageNo",
                "ps":"pageSize"
            },
            "itemModule":{
                "type":"custom_component",
                "name":"company-state-to-enforcement"
            }
        }
    }
}


### 获取页面数据
POST {{endpoint}}/data/120 HTTP/1.1
content-type: application/json

{
    "type": {
      "list": [
        { 
						"id": "131", 
						"year": "2021年",
						"startTime": "4月1日",
						"endTime": "4月5日",
						"cellList":[
							{"id": "121", "title": "4月1日"},
							{"title": "4月2日"},
							{"title": "4月3日"},
							{"title": "4月4日"}
						]
					},
					{
						"id": "132", 
						"year": "2021年",
						"startTime": "5月1日",
						"endTime": "5月5日",
						"cellList":[
							{"id": "122", "title": "5月1日" },
							{"title": "5月2日"},
							{"title": "5月3日"},
							{"title": "5月4日"},
							{"title": "5月5日"}
						]
					},
					{
						"id": "133", 
						"year": "2021年",
						"startTime": "6月1日",
						"endTime": "6月3日",
						"cellList":[
							{"id": "123", "title": "6月1日"},
							{"title": "6月2日"},
							{"title": "6月3日"}
						]
					}
      ],
      "total": 3
    }
  }

