@endpoint=https://api.mock.smallsaas.cn


### 页面测试数据
GET  {{endpoint}}/data?id=100 HTTP/1.1
content-type: application/json

{
    "avatar": "",
    "userName": "张三",
    "enterpriseNumber": "Ab263549898",
    "domainName": "hajdshdjAb263549898",
    "job": "员工"
}
