@endpoint=https://ai.hdqmjs.com


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/110
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "自查记录", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "bindingTarget": "data",
          "key":"7d0e7714-d265-11eb-af94-0800271e55b7",
          "container":{
            "height":""
          }
        }
        
    ], 
    "moduleData": {
        "7d0e7714-d265-11eb-af94-0800271e55b7": {
          "loadApi":"https://ai.hdqmjs.com/api.flow.process/instanceListPage",
          "method":"POST",
          "itemNavigation": "/companyHome/selfExplain?piId",
          "response":{
              "list":"list"
          },
          "response":{
            "list":"list"
          },
          "request":{
            "default":{
              "dataScope": 1,
              "processDefinitionKey": "zc"
            },
              "pn":"pageNo",
              "ps":"pageSize"
          },
          "itemModule":{
            "type":"custom_component",
            "name":"stateToItem"
          }
        }
    }
}


### 获取页面数据
POST {{endpoint}}/data/110 HTTP/1.1
content-type: application/json

{
    "type": {
      "list": [
        {
          "id": "311",
          "type": "100",
          "name": "2020年第一季度",
          "code": "2020-01-01 - 2020-03-31",
          "createTime": "2020-3-25 12:12:12",
          "status": "START"
        },
        {
          "id": "321",
          "type": "200",
          "name": "2020年第二季度",
          "code": "2020-01-01 - 2020-05-31",
          "createTime": "2020-3-25 12:12:12",
          "status": "VERIFYING"
        },
        
        {
          "id": "322",
          "type": "200",
          "name": "2020年第二季度",
          "code": "2020-01-01 - 2020-05-31",
          "createTime": "2020-3-25 12:12:12",
          "status": "CLOSE_REJECTED"
        },
        
        {
          "id": "323",
          "type": "200",
          "name": "2020年第二季度",
          "code": "2020-01-01 - 2020-05-31",
          "createTime": "2020-3-25 12:12:12",
          "status": "CLOSE_APPROVED"
        }
      ],
      "total": 3
    }
  }

