@endpoint=https://api.mock.smallsaas.cn


## 动态列表

### 保存动态列表
POST {{endpoint}}/form/110
content-type: application/json

{
    "version": "1", 
    "name": "page_home", 
    "title": "自查记录", 
    "pageStyle": { }, 
    "loadApi": "https://api.mock.smallsaas.cn/data?id=200", 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {
        "padding": "10px", 
        "margin": "10px", 
        "fill": "white", 
        "stroke": {
            "color": "lightgray", 
            "lineWidth": "1px"
        }, 
        "shadow": {
            "radius": 5
        }, 
        "corner": "8px", 
        "spacing": "1em"
    }, 
    "modules": [
        {
          "type": "autolist",
          "tips": "动态列表组件",
          "binding":
          {
            "list":"list",
            "total":"total"
          },
          "bindingTarget": "data",
          "key":"7d0e7714-d265-11eb-af94-0800271e55b7",
          "container":{
            "height":""
          }
        }
        
    ], 
    "moduleData": {
        "7d0e7714-d265-11eb-af94-0800271e55b7": {
          "loadApi":"https://api.mock.smallsaas.cn/data?id=110",
         "itemNavigation": "/companyHome/my/selfInspectionDetail?id",
          "response":{
              "list":"type.list",
              "total":"type.total"
          },
          "tabConfig":{
            "field":"type",
            "show":true
          },
          "response":{
            "list":"type.list",
            "total":"type.total"
          },
          "request":{
            "fixed":"type",
            "default":{
              "type":"0"
            },
            "pn":"pageNo",
            "ps":"pageSize"
          },
          "itemModule":{
            "type":"custom_component",
            "name":"SelfInspectionRecordItem"
          }
        }
    }
}


### 获取页面数据
POST {{endpoint}}/data/110 HTTP/1.1
content-type: application/json

# {
#     "record": [
#       {
#         "type": "100",
#         "title": "2020年第一季度",
#         "startTime": "2020-01-01",
#         "endTime": "2020-03-31",
#         "submitTime": "2020-3-25 12:12:12",
#         "status": "pass"
#       },
#       {
#         "type": "100",
#         "title": "2020年第一季度",
#         "startTime": "2020-01-01",
#         "endTime": "2020-03-31",
#         "submitTime": "2020-3-25 12:12:12",
#         "status": "failed"
#       }
#     ],
#     "total": 2
# }


{
    "type": {
      "list": [
        {
          "id": "311",
          "type": "100",
          "title": "2020年第一季度",
          "startTime": "2020-01-01",
          "endTime": "2020-03-31",
          "submitTime": "2020-3-25 12:12:12",
          "status": "pass"
        },
        {
          "id": "321",
          "type": "200",
          "title": "2020年第二季度",
          "startTime": "2020-01-01",
          "endTime": "2020-05-31",
          "submitTime": "2020-3-25 12:12:12",
          "status": "failed"
        }
      ],
      "total": 3
    }
  }

