@endpoint=https://ai.hdqmjs.com
@token = eyJleHBpcmVzX2luIjp7ImRheU9mTW9udGgiOjI2LCJkYXlPZldlZWsiOiJUVUVTREFZIiwiZGF5T2ZZZWFyIjoyOTksImhvdXIiOjE5LCJtaW51dGUiOjIxLCJtb250aCI6Ik9DVE9CRVIiLCJtb250aFZhbHVlIjoxMCwibmFubyI6NTE5MDAwMDAwLCJzZWNvbmQiOjIxLCJ5ZWFyIjoyMDIxLCJjaHJvbm9sb2d5Ijp7ImNhbGVuZGFyVHlwZSI6Imlzbzg2MDEiLCJpZCI6IklTTyJ9fSwidG9rZW5fdHlwZSI6IkJlYXJlciIsInNjb3BlIjoic2VydmVyIiwiYWxnIjoiSFMyNTYifQ.eyJhY2Nlc3NfdG9rZW4iOiJkMzBhOTY1MTNlNTc0Y2ViOTdiMGNhYjlkNDAzY2RlMyIsInJlZnJlc2hfdG9rZW4iOiI5M2U3MTljZWI3N2E0NjAwOTRlY2RmNDFlYTFmYTEwYSIsImV4cGlyZXNfaW4iOjg2NDAwMCwidXNlcl9pZCI6ODMzNywiZGVwdF9pZCI6MzMsInVzZXJuYW1lIjoiMTgyMGI0MmUyZDMyNGMzMWE5ZDE2NTgzZWFkMzhiYTEiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic2NvcGUiOiJzZXJ2ZXIiLCJsaWNlbmNlIjoicHJvZ3Jlc3MiLCJmcm9tIjoyLCJ0aW1lX3N0YW1wIjoiMTYzNDM4MzI4MSIsInJvbGVfY29kZXMiOlsiUVlZSCJdLCJuaWNrbmFtZSI6IuWMl-S6rOatpuaWl-Wjq-S9k-iCsuS6p-S4mueuoeeQhuaciemZkOWFrOWPuCIsIm9wZW5faWQiOiJvSzBrLTR6MWJZYXktT0l3Uy1iTTd4ZkFhb1NFIiwiYXBwIjoiaW50ZXJuYWwifQ.PBc6Jd8uIQ6lcPqlRJwdkSOtLHmdke1w96xMgKdo4R8
POST {{endpoint}}/api.flow.task/taskListPage
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "formType":"fg",
    "pageNo":1,
    "pageSize":10,
    "queryType":"wait"
}