@endpoint=https://api.mock.smallsaas.cn


GET {{endpoint}}/form?id=12000
### 
POST {{endpoint}}/form/12000
content-type: application/json

{
    "version":"1",
    "name":"addCompany",
    "title":"增加企业",
    "pageStyle":{},
    "loadApi":"",
    "request":{
    },
    "response":{
        "data":"data"
    },
    "moduleContainer":{
    },
    "modules":[
        {
            "type":"autoform",
            "key":"555sd22-ad44-55ea-ca11-4225534d52b7",
            "name":"autoform",
            "container":{
                "background":"white"
            },
            "FormKey":"yyzz",
            "API":"/api.page.design.form/loadFormInfo"
        }
    ]
}